import assert from "node:assert/strict";
import test from "node:test";
import { createEmptyAssessment } from "../lib/initial-state.ts";
import { getCalibrationProfile, setCalibrationAnswer } from "../lib/calibration.ts";
import { generateExpectedWorkflowReviews, materialityReasons, reviewExpectedWorkflow, updateWorkflowEstimate } from "../lib/workflow-methodology.ts";

function calibratedCpa(){let assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.websiteDiscovery.status="confirmed";const profile=getCalibrationProfile(assessment.company_profile.industry);for(const [id,value] of [["annual_revenue",5_500_000],["employee_count",46],["locations",2],["tax_filings",3100]] as const){assessment=setCalibrationAnswer(assessment,profile.fields.find((field)=>field.id===id)!,"exact",value);}assessment.businessCalibration.status="complete";return assessment;}
test("does not generate workflow cards before calibration",()=>{const assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.websiteDiscovery.status="confirmed";assert.equal(generateExpectedWorkflowReviews(assessment).length,0);});
test("typing/saving calibration values does not complete the step without explicit continue",()=>{let assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.websiteDiscovery.status="confirmed";const profile=getCalibrationProfile(assessment.company_profile.industry);for(const [id,value] of [["annual_revenue",5_500_000],["employee_count",46],["locations",2],["tax_filings",3100]] as const)assessment=setCalibrationAnswer(assessment,profile.fields.find((field)=>field.id===id)!,"exact",value);assert.equal(assessment.businessCalibration.status,"in_progress");assert.equal(generateExpectedWorkflowReviews(assessment).length,0);});
test("generates an industry-specific inventory after calibration",()=>{const reviews=generateExpectedWorkflowReviews(calibratedCpa());assert.ok(reviews.some((item)=>/engagement letter/i.test(item.workflowName)));assert.ok(reviews.every((item)=>item.status==="unreviewed"));});
test("uses a confirmed volume driver to narrow a CPA estimate",()=>{const assessment=calibratedCpa(),reviews=generateExpectedWorkflowReviews(assessment),tax=reviews.find((item)=>item.workflowName==="Tax return preparation")!;assert.deepEqual(tax.estimatedAnnualVolume,{min:2790,max:3410,unit:"returns"});assert.ok(tax.calculationBasis?.some((item)=>item.includes("tax filings")));});
test("editing volume recalculates annual effort",()=>{const assessment=calibratedCpa();assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const estimate=assessment.expectedWorkflowReviews.find((item)=>/engagement letter/i.test(item.workflowName))!;const before=estimate.estimatedAnnualHours!.max;const updated=updateWorkflowEstimate(assessment,estimate.id,{estimatedAnnualVolume:{min:4000,max:5000,unit:"engagements"}}),after=updated.expectedWorkflowReviews.find((item)=>item.id===estimate.id)!;assert.ok(after.estimatedAnnualHours!.max>before);assert.equal(after.sourceType,"user_corrected");});
test("accepting an estimate creates a benchmark-labeled workflow with annual effort",()=>{const assessment=calibratedCpa();assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const estimate=assessment.expectedWorkflowReviews[0],updated=reviewExpectedWorkflow(assessment,estimate.id,"exists");assert.equal(updated.workflows.length,1);assert.ok((updated.workflows[0].annual_time_cost_hours??0)>0);});
test("materiality captures time, volume, exceptions, impact, and document dependence",()=>{const assessment=calibratedCpa();assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const updated=reviewExpectedWorkflow(assessment,assessment.expectedWorkflowReviews[0].id,"exists"),workflow=updated.workflows[0];workflow.weekly_time_cost_hours=8;workflow.monthly_volume=100;workflow.bottlenecks=["Repeated follow-up"];workflow.documents_used=["Engagement letters"];workflow.financial_impact=4;assert.ok(materialityReasons(workflow).length>=4);});
test("excluding an accepted estimate removes it from scoring",()=>{const assessment=calibratedCpa();assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const id=assessment.expectedWorkflowReviews[0].id,accepted=reviewExpectedWorkflow(assessment,id,"exists"),excluded=reviewExpectedWorkflow(accepted,id,"not_material");assert.equal(excluded.workflows.length,0);assert.equal(excluded.opportunities.length,0);});
