import assert from "node:assert/strict";
import test from "node:test";
import { createEmptyAssessment } from "../lib/initial-state.ts";
import { generateExpectedWorkflowReviews, materialityReasons, reviewExpectedWorkflow } from "../lib/workflow-methodology.ts";

test("generates an industry-specific expected workflow inventory",()=>{const assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.company_profile.employee_count=30;assessment.company_profile.locations=2;const reviews=generateExpectedWorkflowReviews(assessment);assert.ok(reviews.some((item)=>/engagement letter/i.test(item.workflowName)));assert.ok(reviews.every((item)=>item.sourceType==="industry_benchmark"));assert.ok(reviews.every((item)=>item.status==="unreviewed"));});
test("accepting an estimate creates a benchmark-labeled workflow with annual effort",()=>{const assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.company_profile.employee_count=25;assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const estimate=assessment.expectedWorkflowReviews[0];assert.ok(estimate.estimatedAnnualVolume);assert.ok(estimate.estimatedAnnualHours);const updated=reviewExpectedWorkflow(assessment,estimate.id,"exists");assert.equal(updated.workflows.length,1);assert.equal(updated.workflows[0].sourceType,"industry_benchmark");assert.equal(updated.workflows[0].confidence,"benchmark_assumption");assert.ok((updated.workflows[0].annual_time_cost_hours??0)>0);});
test("materiality captures time, volume, exceptions, impact, and document dependence",()=>{const assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const updated=reviewExpectedWorkflow(assessment,assessment.expectedWorkflowReviews[0].id,"exists");const workflow=updated.workflows[0];workflow.weekly_time_cost_hours=8;workflow.monthly_volume=100;workflow.bottlenecks=["Repeated follow-up"];workflow.documents_used=["Engagement letters"];workflow.financial_impact=4;assert.ok(materialityReasons(workflow).length>=4);});
test("excluding an accepted estimate removes it from workflows and opportunity scoring",()=>{const assessment=createEmptyAssessment();assessment.company_profile.industry="CPA/accounting firms";assessment.expectedWorkflowReviews=generateExpectedWorkflowReviews(assessment);const id=assessment.expectedWorkflowReviews[0].id;const accepted=reviewExpectedWorkflow(assessment,id,"exists");assert.equal(accepted.workflows.length,1);const excluded=reviewExpectedWorkflow(accepted,id,"not_material");assert.equal(excluded.workflows.length,0);assert.equal(excluded.opportunities.length,0);});
