export type Score = 1 | 2 | 3 | 4 | 5;
export type ExportCapability = "none" | "manual" | "csv" | "api" | "unknown";
export type IntegrationCapability = "none" | "limited" | "good" | "strong" | "unknown";
export type OpportunityClassification = "Quick Win" | "Near-Term Project" | "Foundation Project" | "Future Opportunity";
export type FactSourceType = "user_confirmed" | "user_estimate" | "website" | "industry_benchmark" | "system_inferred" | "unknown_verifiable" | "excluded_by_user";
export type FactConfidence = "exact" | "estimate" | "range" | "benchmark_assumption" | "inferred" | "unknown" | "excluded";
export type FactValue = string | number | { min: number; max: number };
export interface CapturedFact { id: string; label: string; value: FactValue; unit: string; timePeriod: string; businessArea: string; workflowId?: string; sourceType: FactSourceType; sourceUrl?: string; confidence: FactConfidence; verificationSources: string[]; relatedFields: string[]; createdFromUserAnswer: string; createdAt: string; needsClarification?: boolean; needsConfirmation?: boolean; confirmedByUser?: boolean; }
export type DiscoveryIssueType = "missing_information" | "user_estimate" | "benchmark_assumption" | "conflicting_information" | "needs_verification" | "excluded_variable";
export type DiscoveryIssueStatus = "open" | "accepted_for_draft" | "verified" | "excluded" | "resolved";
export interface DiscoveryIssue { id:string; issueType:DiscoveryIssueType; label:string; description:string; businessArea:string; workflowId?:string; relatedReportSection:string; requestedValue:string; currentValue?:FactValue; unit:string; timePeriod:string; sourceType:FactSourceType; confidence:FactConfidence; verificationSources:string[]; recommendedNextAction:string; effectOnReadiness:string; effectOnScoring:string; notes:string; status:DiscoveryIssueStatus; createdAt:string; updatedAt:string; }
export type WebsiteReviewStatus="not_started"|"pending_review"|"confirmed";
export interface WebsiteDiscoveryReview { status:WebsiteReviewStatus; companyName:string; industry:string; businessDescription:string; services:string[]; customerSegments:string[]; locations:string[]; revenueModelClues:string[]; leadershipClues:string[]; hiringSignals:string[]; technologyMentioned:string[]; likelyBusinessFunctions:string[]; likelyWorkflows:string[]; complianceConstraints:string[]; sourceUrls:string[]; rejectedFactLabels:string[]; confirmedAt?:string; }
export type ExpectedWorkflowStatus="unreviewed"|"exists"|"does_not_exist"|"outsourced"|"not_material"|"needs_discussion"|"missed_add";
export interface ExpectedWorkflowReview { id:string; workflowName:string; businessFunction:string; rationale:string; sourceType:FactSourceType; confidence:FactConfidence; sourceUrls:string[]; status:ExpectedWorkflowStatus; materialityReasons:string[]; relatedWorkflowId?:string; reviewedAt?:string; }

export interface CompanyProfile {
  company_name: string; website_url: string; industry: string; subindustry: string; locations: number | null;
  employee_count: number | null; annual_revenue: number | null; years_in_business: number | null;
  customer_types: string[]; revenue_sources: string[]; operating_model: string;
  management_structure: string; strategic_priorities: string[]; current_business_pressures: string[];
}
export interface OperatingMetric { metric_name: string; value: number; unit: string; period: string; source: string; business_context: string; }
export interface MetricTarget { metric_name: string; baseline: string; target: string; measurement_period: string; source: string; }
export interface BusinessFunction { function_name: string; employee_count: number | null; manager_owner: string; importance: Score; pain_level: Score; systems_used: string[]; notes: string; }
export interface RoleGroup { role_name: string; function_name: string; headcount: number | null; responsibilities: string[]; pain_points: string[]; turnover_level: string; hiring_difficulty: Score; ai_adoption_likelihood: Score; }
export interface Workflow { workflow_name: string; function_name: string; owner: string; trigger: string; steps: string[]; inputs: string[]; outputs: string[]; systems_used: string[]; documents_used: string[]; people_involved: string[]; number_people_involved?:number|null; frequency: string; monthly_volume: number | null; time_per_instance_minutes: number | null; weekly_time_cost_hours: number | null; monthly_time_cost_hours?:number|null; annual_time_cost_hours?:number|null; seasonality?:string; exception_rate_percent?:number|null; cycle_time?:string; verification_sources?:string[]; sourceType?:FactSourceType; confidence?:FactConfidence; materiality_status?:"unreviewed"|"material"|"not_material"; materiality_reasons?:string[]; error_or_rework_level: Score; bottlenecks: string[]; decision_points: string[]; customer_impact: Score; financial_impact: Score; data_sensitivity: Score; process_maturity: Score; data_readiness: Score; ai_candidate_notes: string; data_sources?: string[]; current_process_quality?: string; business_impact?: string; baseline_metrics?: MetricTarget[]; target_metrics?: MetricTarget[]; implementation_dependencies?: string[]; suggested_ai_use_cases?: string[]; roadmap_phase?: string; pilot_timing?: string; success_measures?: string[]; implementation_complexity_factors?: string[]; }
export interface TechnologySystem { system_name: string; vendor: string; function_served: string; users: string; data_stored: string[]; export_capability: ExportCapability; integration_capability: IntegrationCapability; satisfaction: Score; limitations: string[]; }
export interface DataAsset { asset_name: string; source_system: string; data_type: string; owner: string; format: string; cleanliness: Score; accessibility: Score; update_frequency: string; sensitivity: Score; ai_usability: Score; }
export interface DocumentAsset { document_type: string; location: string; owner: string; quality: Score; update_frequency: string; ai_use_cases: string[]; }
export interface PainPoint { pain_point: string; function_name: string; workflow_name: string; who_feels_it: string[]; frequency: string; severity: Score; time_cost: string; dollar_cost: string; customer_impact: Score; employee_impact: Score; current_workaround: string; root_cause: string; }
export interface AIReadiness { current_ai_use: string; leadership_support: Score | null; employee_readiness: Score | null; data_availability: Score | null; data_organization: Score | null; process_documentation: Score | null; governance_maturity: Score | null; implementation_capacity: Score | null; data_sensitivity_concerns: string[]; budget_appetite: string; timeline_expectation: string; formal_ai_policy?: boolean; structured_ai_training?: boolean; implementation_constraints?: string[]; }
export interface GovernanceProfile { sensitive_data_types: string[]; requires_human_approval: string[]; regulated_constraints: string[]; brand_review_needs: boolean; employee_decision_controls: boolean; vendor_or_customer_data_rules: string[]; }
export interface Opportunity { opportunity_name: string; related_workflow: string; description: string; business_value_score: Score; frequency_score: Score; repetition_score: Score; data_readiness_score: Score; adoption_score: Score; strategic_fit_score: Score; implementation_difficulty_score: Score; risk_score: Score; total_score: number; complexity: string; classification: OpportunityClassification; recommended_phase: string; time_to_pilot: string; success_metrics: string[]; owner?: string; business_evidence?: string[]; baseline_metrics?: MetricTarget[]; target_metrics?: MetricTarget[]; implementation_dependencies?: string[]; tool_categories?: string[]; }
export interface RoadmapPhase { phase_name: string; timeframe: string; objectives: string[]; opportunity_names: string[]; dependencies: string[]; success_measures: string[]; }
export interface Answer { question_id: string; module: QuestionModuleId; field: string; answer: string; saved_at: string; }
export type QuestionModuleId = "company_profile" | "operating_metrics" | "business_functions" | "people_roles" | "workflows" | "workflow_detail" | "technology_stack" | "data_readiness" | "current_ai_use" | "pain_points" | "baseline_metrics" | "strategic_priorities" | "governance_risk" | "implementation_capacity" | "success_metrics";
export interface Assessment { id: string; created_at: string; updated_at: string; company_profile: CompanyProfile; websiteDiscovery:WebsiteDiscoveryReview; expectedWorkflowReviews:ExpectedWorkflowReview[]; capturedFacts: CapturedFact[]; discoveryIssues: DiscoveryIssue[]; operating_metrics: OperatingMetric[]; business_functions: BusinessFunction[]; role_groups: RoleGroup[]; workflows: Workflow[]; technology_stack: TechnologySystem[]; data_assets: DataAsset[]; document_assets: DocumentAsset[]; pain_points: PainPoint[]; ai_readiness: AIReadiness; governance_profile: GovernanceProfile; management_decisions: string[]; opportunities: Opportunity[]; roadmap_phases: RoadmapPhase[]; answers: Answer[]; }
export interface AssessmentQuestion { id: string; module: QuestionModuleId; field: string; title: string; help: string; priority: number; isComplete: (assessment: Assessment) => boolean; }
export interface ReadinessSection { key: string; label: string; weight: number; complete: boolean; missing: string[]; }
