"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createEmptyAssessment } from "@/lib/initial-state";
import { loadAssessment } from "@/lib/storage";
import { calculateReadiness } from "@/lib/readiness";
import { issueCounts } from "@/lib/discovery-issues";
import type { Assessment, DiscoveryIssue } from "@/types/assessment";
import { appendStoredTrace } from "@/lib/trace";

const value=(issue:DiscoveryIssue)=>typeof issue.currentValue==="object"?`${issue.currentValue.min}-${issue.currentValue.max}`:issue.currentValue===undefined?"Not available":String(issue.currentValue);
function IssueTable({title,items}:{title:string;items:DiscoveryIssue[]}) { return <section><h2>{title}</h2>{items.length?<div className="report-table-wrap"><table><thead><tr><th>Item</th><th>Current value</th><th>Context</th><th>Source / confidence</th><th>Effect</th><th>Next action / verification</th></tr></thead><tbody>{items.map((issue)=><tr key={issue.id}><td><strong>{issue.label}</strong><small>{issue.description}</small></td><td>{value(issue)} {issue.unit}</td><td>{issue.businessArea}<small>{issue.workflowId||issue.relatedReportSection} · {issue.timePeriod}</small></td><td>{issue.sourceType.replaceAll("_"," ")}<small>{issue.confidence} · {issue.status}</small></td><td>{issue.effectOnReadiness}<small>{issue.effectOnScoring}</small></td><td>{issue.recommendedNextAction}<small>{issue.verificationSources.join(", ")||"Ask the process owner or check the source system."}</small></td></tr>)}</tbody></table></div>:<p>None recorded.</p>}</section>; }

export function DiscoveryIssuesReport() {
  const [assessment,setAssessment]=useState<Assessment>(()=>createEmptyAssessment("1970-01-01T00:00:00.000Z")); const [generatedAt,setGeneratedAt]=useState(""); const [printAttempted,setPrintAttempted]=useState(false);
  useEffect(()=>{const timer=window.setTimeout(()=>{setAssessment(loadAssessment()??createEmptyAssessment());setGeneratedAt(new Date().toLocaleString());appendStoredTrace({eventType:"report_generated",message:"Discovery issues report generated.",affectedId:"discovery_issues_report",source:"system"});},0);return()=>window.clearTimeout(timer);},[]);
  const readiness=calculateReadiness(assessment),counts=issueCounts(assessment),issues=assessment.discoveryIssues??[];
  const print=()=>{appendStoredTrace({eventType:"print_triggered",message:"Discovery issues report print requested.",affectedId:"discovery_issues_report",source:"user"});setPrintAttempted(true);window.print();};
  return <main className="report-shell discovery-issues-shell"><header className="hero compact no-print"><div><span className="eyebrow">Discovery working paper</span><h1>Estimates &amp; missing information</h1><p>Use this printable checklist to collect, verify, replace, or deliberately exclude uncertain inputs.</p></div><div className="header-actions"><Link className="secondary link-control" href="/">Back to interview</Link><button className="print-button" onClick={print}>Print Discovery Issues Report</button></div></header>
    <article className="report-preview" aria-label="Discovery Estimates, Assumptions and Missing Information Report">{printAttempted&&<p className="print-fallback no-print">If the embedded browser does not open a print dialog, open this URL in a regular browser and press Ctrl+P.</p>}<div className="report-document discovery-issues-report"><h1>Discovery Estimates, Assumptions &amp; Missing Information Report</h1><p className="report-company">{assessment.company_profile.company_name||"Company not yet identified"}</p><p><strong>Generated:</strong> {generatedAt||"Preparing..."}<br/><strong>Assessment readiness:</strong> {readiness.percent}%<br/><strong>Purpose:</strong> Working checklist for improving the evidence behind the AI roadmap.</p>
      <section><h2>Summary</h2><div className="issue-summary">{Object.entries({"Confirmed facts":counts.confirmed,"User estimates":counts.estimates,"Benchmark assumptions":counts.benchmarks,"Missing items":counts.missing,"Excluded variables":counts.excluded,"Conflicts":counts.conflicts,"Verification needed":counts.verification}).map(([label,count])=><div key={label}><strong>{count}</strong><span>{label}</span></div>)}</div></section>
      <IssueTable title="User estimates" items={issues.filter((i)=>i.issueType==="user_estimate")}/><IssueTable title="Industry benchmark assumptions" items={issues.filter((i)=>i.issueType==="benchmark_assumption")}/><IssueTable title="Missing information" items={issues.filter((i)=>i.issueType==="missing_information"||i.issueType==="needs_verification")}/><IssueTable title="Excluded variables" items={issues.filter((i)=>i.issueType==="excluded_variable"||i.status==="excluded")}/><IssueTable title="Conflicting information" items={issues.filter((i)=>i.issueType==="conflicting_information")}/>
      <section><h2>Recommended information to collect before finalizing</h2>{issues.filter((i)=>!["verified","resolved","excluded"].includes(i.status)).length?<ol>{issues.filter((i)=>!["verified","resolved","excluded"].includes(i.status)).map((issue)=><li key={issue.id}><strong>{issue.label}:</strong> {issue.recommendedNextAction} Suggested sources: {issue.verificationSources.join(", ")||"process owner, source system, management report, or supporting document"}.</li>)}</ol>:<p>No open collection items are recorded.</p>}</section>
    </div></article></main>;
}
