"use client";
import { useState } from "react";
import type { Assessment, WebsiteDiscoveryReview } from "@/types/assessment";
import { confirmWebsiteDiscovery } from "@/lib/website-apply";

const arrayFields:{key:keyof WebsiteDiscoveryReview;label:string}[]=[{key:"services",label:"Services / products"},{key:"customerSegments",label:"Customer segments"},{key:"locations",label:"Locations"},{key:"revenueModelClues",label:"Revenue model clues"},{key:"leadershipClues",label:"Leadership / management clues"},{key:"hiringSignals",label:"Hiring / career clues"},{key:"technologyMentioned",label:"Technology clues"},{key:"likelyBusinessFunctions",label:"Likely business functions"},{key:"likelyWorkflows",label:"Likely workflows"},{key:"complianceConstraints",label:"Compliance or industry constraints"}];
const lines=(value:string)=>value.split(/\n|;/).map((item)=>item.trim()).filter(Boolean);
export function WebsiteFactsReview({assessment,onConfirm}:{assessment:Assessment;onConfirm:(next:Assessment)=>void}) { const [review,setReview]=useState(assessment.websiteDiscovery); const set=(key:keyof WebsiteDiscoveryReview,value:unknown)=>setReview((current)=>({...current,[key]:value})); const toggleReject=(label:string)=>setReview((current)=>({...current,rejectedFactLabels:current.rejectedFactLabels.includes(label)?current.rejectedFactLabels.filter((item)=>item!==label):[...current.rejectedFactLabels,label]}));
  return <div className="website-review"><span className="step">Website discovery · editable review</span><h2>Confirm or correct the company facts</h2><p className="help">These are website-derived inferences, not confirmed facts. Edit them, reject unsupported categories, then confirm to enter industry expert mode.</p><div className="review-grid"><label>Company name<input value={review.companyName} onChange={(e)=>set("companyName",e.target.value)}/></label><label>Industry<input value={review.industry} onChange={(e)=>set("industry",e.target.value)}/></label><label className="span-two">Business description<textarea value={review.businessDescription} onChange={(e)=>set("businessDescription",e.target.value)}/></label>{arrayFields.map(({key,label})=><label key={String(key)} className="review-field"><span>{label}</span><textarea value={(review[key] as string[]).join("\n")} onChange={(e)=>set(key,lines(e.target.value))}/><span className="review-meta">Source: website · confidence: inferred</span><button type="button" className={review.rejectedFactLabels.includes(label)?"secondary rejected":"secondary"} onClick={()=>toggleReject(label)}>{review.rejectedFactLabels.includes(label)?"Rejected · restore":"Reject this category"}</button></label>)}</div><div className="website-sources"><strong>Website source URLs</strong>{review.sourceUrls.map((url)=><a href={url} target="_blank" rel="noreferrer" key={url}>{url}</a>)}</div><div className="actions"><button onClick={()=>onConfirm(confirmWebsiteDiscovery(assessment,review))} disabled={!review.companyName.trim()||!review.industry.trim()}>Confirm facts &amp; load industry workflows</button></div></div>;
}
