"use client";
import type { Assessment } from "@/types/assessment";
import { confirmWebsiteDiscovery, type EditableWebsiteField, updateWebsiteDiscoveryField } from "@/lib/website-apply";

const arrayFields:{key:EditableWebsiteField;label:string}[]=[{key:"services",label:"Services / products"},{key:"customerSegments",label:"Customer segments"},{key:"locations",label:"Locations"},{key:"revenueModelClues",label:"Revenue model clues"},{key:"leadershipClues",label:"Leadership / management clues"},{key:"hiringSignals",label:"Hiring / career clues"},{key:"technologyMentioned",label:"Technology clues"},{key:"likelyBusinessFunctions",label:"Likely business functions"},{key:"likelyWorkflows",label:"Likely workflows"},{key:"complianceConstraints",label:"Compliance or industry constraints"}];
const lines=(value:string)=>value.split("\n").map((item)=>item.trimStart());
const industries=["CPA/accounting firms","Law firms","Restaurants/hospitality","Staffing/recruiting firms","Professional services firms","Light manufacturing/distribution","Construction/trades/service businesses"];
export function WebsiteFactsReview({assessment,onChange,onConfirm}:{assessment:Assessment;onChange:(next:Assessment)=>void;onConfirm:(next:Assessment)=>void}) { const review=assessment.websiteDiscovery,source=review.sourceUrls[0]||"Public website"; const update=(field:EditableWebsiteField,value:string|string[])=>onChange(updateWebsiteDiscoveryField(assessment,field,value)); const toggleReject=(label:string)=>{const next=structuredClone(assessment);next.websiteDiscovery.rejectedFactLabels=next.websiteDiscovery.rejectedFactLabels.includes(label)?next.websiteDiscovery.rejectedFactLabels.filter((item)=>item!==label):[...next.websiteDiscovery.rejectedFactLabels,label];next.updated_at=new Date().toISOString();onChange(next);}; const badge=(field:EditableWebsiteField)=><small className={review.correctedFields.includes(field)?"fact-badge corrected":"fact-badge"}>{review.correctedFields.includes(field)?"User corrected · exact":`Website · inferred · ${source}`}</small>;
  return <div className="website-review"><span className="step">Website discovery · editable review</span><h2>Confirm or correct the company facts</h2><p className="help">Every field below is editable. Changes update the working company profile and evidence ledger immediately while retaining the original website value and source.</p><div className="review-grid"><label>Company name<input value={review.companyName} onChange={(e)=>update("companyName",e.target.value)}/>{badge("companyName")}</label><label>Industry<input list="supported-industries" value={review.industry} onChange={(e)=>update("industry",e.target.value)}/><datalist id="supported-industries">{industries.map((industry)=><option value={industry} key={industry}/>)}</datalist>{badge("industry")}</label><label className="span-two">Business description<textarea value={review.businessDescription} onChange={(e)=>update("businessDescription",e.target.value)}/>{badge("businessDescription")}</label>{arrayFields.map(({key,label})=><label key={key} className="review-field"><span>{label}</span><textarea value={(review[key] as string[]).join("\n")} onChange={(e)=>update(key,lines(e.target.value))} placeholder="One item per line"/>{badge(key)}<button type="button" className={review.rejectedFactLabels.includes(label)?"secondary rejected":"secondary"} onClick={()=>toggleReject(label)}>{review.rejectedFactLabels.includes(label)?"Rejected · restore":"Reject this category"}</button></label>)}</div><div className="website-sources"><strong>Website source URLs</strong>{review.sourceUrls.map((url)=><a href={url} target="_blank" rel="noreferrer" key={url}>{url}</a>)}</div><div className="actions"><button onClick={()=>onConfirm(confirmWebsiteDiscovery(assessment,assessment.websiteDiscovery))} disabled={!review.companyName.trim()||!review.industry.trim()}>Confirm company facts and continue</button></div></div>;
}
