"use client";
import { useState } from "react";
import type { Assessment, CalibrationAnswerStatus, ExpectedWorkflowReview, ExpectedWorkflowStatus } from "@/types/assessment";
import type { TraceEntry } from "@/types/trace";
import { calibrationAddressed, getCalibrationProfile, setCalibrationAnswer } from "@/lib/calibration";
import { generateExpectedWorkflowReviews, reviewExpectedWorkflow, updateWorkflowEstimate } from "@/lib/workflow-methodology";

type TraceInput=Omit<TraceEntry,"id"|"timestamp">;
const n=(value:string)=>Math.max(0,Number(value)||0),list=(value:string)=>value.split(/,|\n/).map((item)=>item.trim()).filter(Boolean),display=(value:unknown)=>{if(value&&typeof value==="object"&&"min" in value&&"max" in value){const range=value as {min:unknown;max:unknown};return `${range.min}-${range.max}`;}return value==null?"":String(value);};
const preventEnter=(event:React.KeyboardEvent<HTMLInputElement>,trace:()=>void)=>{if(event.key==="Enter"){event.preventDefault();trace();}};

export function BusinessCalibration({assessment,onSave,onContinue,onTrace}:{assessment:Assessment;onSave:(a:Assessment)=>void;onContinue:(a:Assessment)=>void;onTrace:(e:TraceInput)=>void}){
 const profile=getCalibrationProfile(assessment.company_profile.industry);
 const initial=()=>Object.fromEntries(profile.fields.map((field)=>[field.id,{raw:display(assessment.businessCalibration.answers[field.id]?.value),status:assessment.businessCalibration.answers[field.id]?.status??"unanswered" as CalibrationAnswerStatus}]));
 const [drafts,setDrafts]=useState<Record<string,{raw:string;status:CalibrationAnswerStatus}>>(initial);
 const parse=(raw:string,unit:string)=>{if(unit==="text")return raw;const parts=raw.split(/\s*[-–]\s*/).map(Number).filter(Number.isFinite);return parts.length>1?{min:parts[0],max:parts[1]}:parts.length?parts[0]:null;};
 const applyDrafts=()=>profile.fields.reduce((state,field)=>{const draft=drafts[field.id];return draft&&draft.status!=="unanswered"?setCalibrationAnswer(state,field,draft.status,parse(draft.raw,field.unit)):state;},assessment);
 const validation=profile.fields.filter((field)=>field.required&&!drafts[field.id]?.status||field.required&&drafts[field.id]?.status==="unanswered");
 const save=()=>{const next=applyDrafts();onSave(next);onTrace({eventType:"state_update_applied",message:"Calibration drafts saved without advancing.",affectedId:"business_calibration",source:"user"});};
 const continueNow=()=>{const staged=applyDrafts();if(!calibrationAddressed(staged))return;staged.businessCalibration.status="complete";staged.businessCalibration.completedAt=new Date().toISOString();staged.expectedWorkflowReviews=generateExpectedWorkflowReviews(staged);onContinue(staged);onTrace({eventType:"submit_clicked",message:"Calibration confirmed; generated workflow estimates.",affectedId:"business_calibration",source:"user"});};
 return <div className="calibration"><div className="panel-title"><div><span className="step">Business Size &amp; Complexity Calibration</span><h2>First, narrow the workflow estimates</h2></div><span>{profile.label}</span></div><p className="help">Typing only updates this draft. Nothing advances until you click Continue.</p><div className="calibration-grid">{profile.fields.map((field)=>{const draft=drafts[field.id]??{raw:"",status:"unanswered" as const};return <article key={field.id} className="calibration-field"><label>{field.label}{field.required&&" *"}<input value={draft.raw} placeholder={field.unit==="text"?"Enter systems, separated by commas":`${field.benchmark.min.toLocaleString()}-${field.benchmark.max.toLocaleString()} ${field.unit}`} onKeyDown={(e)=>preventEnter(e,()=>onTrace({eventType:"auto_advance_prevented",message:"Enter was ignored inside a calibration field.",affectedId:field.id,source:"system"}))} onChange={(e)=>{const before=draft.raw,after=e.target.value;setDrafts((current)=>({...current,[field.id]:{raw:after,status:draft.status==="unanswered"?"estimate":draft.status}}));onTrace({eventType:"input_field_changed",message:"Draft changed; no navigation occurred.",affectedId:field.id,before,after,source:"user"});}}/></label><small>{field.help}</small><div className="calibration-actions"><select value={draft.status} onChange={(e)=>{const status=e.target.value as CalibrationAnswerStatus;setDrafts((current)=>({...current,[field.id]:{...draft,status}}));onTrace({eventType:status==="benchmark"?"benchmark_assumption_created":"input_source_changed",message:`Calibration source changed to ${status}.`,affectedId:field.id,before:draft.status,after:status,source:status==="benchmark"?"benchmark":"user"});}}><option value="unanswered">Choose source...</option><option value="exact">Exact</option><option value="estimate">Rough estimate</option><option value="range">Range</option><option value="benchmark">Use benchmark</option><option value="unknown_verifiable">Need to check</option><option value="excluded">Exclude</option></select></div></article>})}</div>{validation.length>0&&<p className="inline-validation">Address each required field before continuing. Exact numbers are not required.</p>}<div className="actions"><button className="secondary" onClick={save}>Save without continuing</button><button onClick={continueNow} disabled={validation.length>0}>Continue to workflow estimates</button></div></div>;
}

function EstimateCard({review,assessment,onSave,onAdvance,onTrace}:{review:ExpectedWorkflowReview;assessment:Assessment;onSave:(a:Assessment)=>void;onAdvance:(a:Assessment)=>void;onTrace:(e:TraceInput)=>void}){
 const [draft,setDraft]=useState(review);
 const set=<K extends keyof ExpectedWorkflowReview>(key:K,value:ExpectedWorkflowReview[K])=>{setDraft((current)=>({...current,[key]:value}));onTrace({eventType:"input_field_changed",message:"Workflow estimate draft changed; no navigation occurred.",affectedId:`${review.id}.${String(key)}`,before:review[key],after:value,source:"user"});};
 const save=()=>{const next=updateWorkflowEstimate(assessment,review.id,draft);onSave(next);onTrace({eventType:"workflow_estimate_edited",message:"Workflow estimate saved without advancing.",affectedId:review.id,source:"user"});};
 const action=(status:ExpectedWorkflowStatus)=>{let next=updateWorkflowEstimate(assessment,review.id,draft);next=reviewExpectedWorkflow(next,review.id,status);onAdvance(next);onTrace({eventType:status==="exists"?"workflow_estimate_accepted":status==="not_material"?"workflow_estimate_excluded":"workflow_marked_for_verification",message:`Workflow action: ${status.replaceAll("_"," ")}.`,affectedId:review.id,source:"user"});};
 const numberInput=(label:string,value:number|undefined,onValue:(value:number)=>void)=><label>{label}<input type="number" value={value??""} onKeyDown={(e)=>preventEnter(e,()=>onTrace({eventType:"auto_advance_prevented",message:"Enter was ignored inside a workflow numeric field.",affectedId:review.id,source:"system"}))} onChange={(e)=>onValue(n(e.target.value))}/></label>;
 return <article className={`workflow-card status-${review.status}`}><div className="workflow-card-head"><div><span className="step">{review.businessFunction}</span><h3>{review.workflowName}</h3></div><span className="classification">{review.status.replaceAll("_"," ")}</span></div><div className="estimate-callouts"><div><small>Estimated annual volume</small><strong>{draft.estimatedAnnualVolume?`${draft.estimatedAnnualVolume.min.toLocaleString()}-${draft.estimatedAnnualVolume.max.toLocaleString()} ${draft.estimatedAnnualVolume.unit}`:"Needs verification"}</strong></div><div><small>Saved annual effort</small><strong>{review.estimatedAnnualHours?`${review.estimatedAnnualHours.min.toLocaleString()}-${review.estimatedAnnualHours.max.toLocaleString()} hours/year`:"Save edits to recalculate"}</strong></div></div><details><summary>Edit estimate</summary><div className="estimate-editor">{numberInput("Annual volume minimum",draft.estimatedAnnualVolume?.min,(value)=>set("estimatedAnnualVolume",{min:value,max:draft.estimatedAnnualVolume?.max??value,unit:draft.estimatedAnnualVolume?.unit??"items"}))}{numberInput("Annual volume maximum",draft.estimatedAnnualVolume?.max,(value)=>set("estimatedAnnualVolume",{min:draft.estimatedAnnualVolume?.min??value,max:value,unit:draft.estimatedAnnualVolume?.unit??"items"}))}{numberInput("Minutes/item minimum",draft.minutesPerItem?.min,(value)=>set("minutesPerItem",{min:value,max:draft.minutesPerItem?.max??value}))}{numberInput("Minutes/item maximum",draft.minutesPerItem?.max,(value)=>set("minutesPerItem",{min:draft.minutesPerItem?.min??value,max:value}))}{numberInput("Exception rate minimum %",draft.exceptionRate?.min,(value)=>set("exceptionRate",{min:value,max:draft.exceptionRate?.max??value}))}{numberInput("Exception rate maximum %",draft.exceptionRate?.max,(value)=>set("exceptionRate",{min:draft.exceptionRate?.min??value,max:value}))}<label>Primary owner<input value={draft.owner??""} onChange={(e)=>set("owner",e.target.value)}/></label><label>Systems used<input value={(draft.commonSystems??[]).join(", ")} onChange={(e)=>set("commonSystems",list(e.target.value))}/></label></div><button className="secondary" onClick={save}>Save estimate without continuing</button></details><div className="calculation-basis"><strong>Calculation basis</strong><ul>{review.calculationBasis?.map((item)=><li key={item}>{item}</li>)}</ul></div><div className="actions workflow-actions"><button onClick={()=>action("exists")}>Accept estimate</button><button className="secondary" onClick={()=>action("needs_discussion")}>Mark for later verification</button><button className="secondary" onClick={()=>action("not_material")}>Exclude from analysis</button></div></article>;
}
export function WorkflowConfirmation({assessment,onSave,onAdvance,onTrace}:{assessment:Assessment;onSave:(a:Assessment)=>void;onAdvance:(a:Assessment)=>void;onTrace:(e:TraceInput)=>void}){const pending=assessment.expectedWorkflowReviews.filter((item)=>item.status==="unreviewed").length;return <div className="workflow-confirmation"><div className="panel-title"><div><span className="step">Calibrated industry workflow estimator</span><h2>Review workflow estimates</h2></div><span>{pending} awaiting action</span></div><p className="help">Edits remain drafts until saved or accepted. Only the explicit action buttons move the workflow forward.</p><div className="workflow-cards">{assessment.expectedWorkflowReviews.map((review)=><EstimateCard key={`${review.id}-${review.reviewedAt??"draft"}`} review={review} assessment={assessment} onSave={onSave} onAdvance={onAdvance} onTrace={onTrace}/>)}</div></div>;}
