import type { Assessment, CalibrationAnswer, CalibrationAnswerStatus, FactConfidence, FactSourceType } from "@/types/assessment";

export interface CalibrationField { id:string; label:string; help:string; unit:string; required:boolean; benchmark:{min:number;max:number}; }
export interface CalibrationProfile { key:string; label:string; fields:CalibrationField[]; }
const field=(id:string,label:string,unit:string,benchmark:[number,number],required=true,help="Used to narrow workflow volume and effort estimates."):CalibrationField=>({id,label,unit,required,benchmark:{min:benchmark[0],max:benchmark[1]},help});
const shared=[field("annual_revenue","Annual revenue or billings","USD/year",[1_000_000,10_000_000]),field("employee_count","Total employees in scope","people",[10,75]),field("locations","Operating locations","locations",[1,3])];
export const calibrationProfiles:Record<string,CalibrationProfile>={
 accounting:{key:"accounting",label:"CPA/accounting firm",fields:[...shared,field("tax_staff","Tax employees","people",[4,25],false),field("cas_staff","Accounting/CAS employees","people",[2,15],false),field("assurance_staff","Audit/assurance employees","people",[2,20],false),field("admin_staff","Administrative employees","people",[2,10],false),field("seasonal_staff","Seasonal/part-time employees","people",[0,15],false),field("tax_filings","Annual tax filings or returns","returns/year",[500,2500]),field("assurance_engagements","Annual audit/review/compilation engagements","engagements/year",[20,100],false),field("cas_clients","Recurring accounting/CAS clients","clients",[30,150],false),field("advisory_projects","Annual advisory/consulting projects","projects/year",[15,100],false),field("new_clients","New clients onboarded annually","clients/year",[30,100],false),field("engagement_renewals","Engagement letters or renewals annually","engagements/year",[300,900],false),field("seasonal_spike","Major seasonal spike intensity (1-5)","rating",[3,5],false),field("core_systems","Core tax, practice, document, billing, communication and e-signature systems","text",[0,0],false)]},
 law:{key:"law",label:"Law firm",fields:[...shared,field("attorneys","Attorneys","people",[5,40]),field("annual_matters","New matters annually","matters/year",[120,800]),field("active_matters","Active matters","matters",[100,1000],false),field("billable_entries","Annual time entries","entries/year",[5000,50000],false)]},
 hospitality:{key:"hospitality",label:"Restaurant/hospitality",fields:[...shared,field("guest_transactions","Annual covers, stays, or guest transactions","transactions/year",[15000,150000]),field("seats_rooms","Seats or rooms in scope","units",[50,300],false),field("events","Annual group events/bookings","events/year",[40,300],false)]},
 staffing:{key:"staffing",label:"Staffing/recruiting",fields:[...shared,field("job_orders","Annual job orders","orders/year",[100,600]),field("candidates","Candidates processed annually","candidates/year",[2000,12000]),field("placements","Annual placements","placements/year",[100,1000],false)]},
 professional_services:{key:"professional_services",label:"Professional services",fields:[...shared,field("projects","Annual client projects","projects/year",[50,400]),field("active_clients","Active clients","clients",[30,250]),field("proposals","Annual proposals","proposals/year",[100,600],false)]},
 construction:{key:"construction",label:"Construction/trades/service",fields:[...shared,field("jobs","Annual jobs or service calls","jobs/year",[300,3000]),field("field_staff","Field employees","people",[8,60]),field("crews","Active crews","crews",[2,15],false)]},
 manufacturing:{key:"manufacturing",label:"Light manufacturing/distribution",fields:[...shared,field("orders","Annual customer orders","orders/year",[1000,15000]),field("skus","Active SKUs","SKUs",[100,3000],false),field("suppliers","Active suppliers","suppliers",[25,300],false)]}
};
export function industryKey(industry:string){const s=industry.toLowerCase();if(/account|cpa/.test(s))return"accounting";if(/law|legal/.test(s))return"law";if(/restaurant|hospitality|hotel/.test(s))return"hospitality";if(/staff|recruit/.test(s))return"staffing";if(/construction|trade|service business/.test(s))return"construction";if(/manufactur|distribution/.test(s))return"manufacturing";return"professional_services";}
export const getCalibrationProfile=(industry:string)=>calibrationProfiles[industryKey(industry)];
export const answerRange=(answer:CalibrationAnswer|undefined):{min:number;max:number}|null=>{if(!answer||answer.status==="excluded"||answer.status==="unknown_verifiable")return null;if(typeof answer.value==="number")return{min:answer.value,max:answer.value};if(answer.value&&typeof answer.value==="object")return answer.value;return null;};
export function calibrationComplete(a:Assessment){const profile=getCalibrationProfile(a.company_profile.industry);return a.websiteDiscovery.status==="confirmed"&&profile.fields.filter((f)=>f.required).every((f)=>a.businessCalibration.answers[f.id]?.status!=="unanswered"&&Boolean(a.businessCalibration.answers[f.id]));}
const source=(status:CalibrationAnswerStatus):{sourceType:FactSourceType;confidence:FactConfidence}=>status==="exact"?{sourceType:"user_confirmed",confidence:"exact"}:status==="estimate"?{sourceType:"user_estimate",confidence:"estimate"}:status==="range"?{sourceType:"user_estimate",confidence:"range"}:status==="benchmark"?{sourceType:"industry_benchmark",confidence:"benchmark_assumption"}:status==="excluded"?{sourceType:"excluded_by_user",confidence:"excluded"}:{sourceType:"unknown_verifiable",confidence:"unknown"};
export function setCalibrationAnswer(a:Assessment,field:CalibrationField,status:CalibrationAnswerStatus,value:number|{min:number;max:number}|string|null){const next=structuredClone(a),now=new Date().toISOString(),quality=source(status);next.businessCalibration.industryKey=industryKey(next.company_profile.industry);next.businessCalibration.status="in_progress";next.businessCalibration.answers[field.id]={fieldId:field.id,value:status==="benchmark"?field.benchmark:value,unit:field.unit,status,...quality,updatedAt:now};if(field.id==="employee_count"&&typeof value==="number")next.company_profile.employee_count=value;if(field.id==="annual_revenue"&&typeof value==="number")next.company_profile.annual_revenue=value;if(field.id==="locations"&&typeof value==="number")next.company_profile.locations=value;next.capturedFacts=next.capturedFacts.filter((f)=>!f.relatedFields.includes(`businessCalibration.${field.id}`));if(status!=="excluded")next.capturedFacts.push({id:`calibration-${field.id}-${Date.now()}`,label:field.label,value:status==="benchmark"?field.benchmark:(value??"Unknown"),unit:field.unit,timePeriod:"Most recent completed year",businessArea:"Business size and complexity",sourceType:quality.sourceType,confidence:quality.confidence,verificationSources:["Company operating report or process owner"],relatedFields:[`businessCalibration.${field.id}`],createdFromUserAnswer:"Business Size & Complexity Calibration",createdAt:now,needsConfirmation:status!=="exact",confirmedByUser:status==="exact"});next.discoveryIssues=next.discoveryIssues.filter((i)=>i.requestedValue!==`businessCalibration.${field.id}`);if(["estimate","range","benchmark","unknown_verifiable","excluded"].includes(status))next.discoveryIssues.push({id:`calibration-issue-${field.id}-${Date.now()}`,issueType:status==="benchmark"?"benchmark_assumption":status==="excluded"?"excluded_variable":status==="unknown_verifiable"?"needs_verification":"user_estimate",label:field.label,description:`Calibration input is ${status.replaceAll("_"," ")}.`,businessArea:"Business size and complexity",relatedReportSection:"Workflow estimates",requestedValue:`businessCalibration.${field.id}`,currentValue:value??undefined,unit:field.unit,timePeriod:"Most recent completed year",sourceType:quality.sourceType,confidence:quality.confidence,verificationSources:["Company operating report or process owner"],recommendedNextAction:status==="excluded"?"No action unless the workflow estimate needs this driver.":"Replace with verified company data when available.",effectOnReadiness:"Partial credit until verified.",effectOnScoring:status==="excluded"?"Not used in estimates.":"Used with reduced confidence.",notes:"Calibration input",status:status==="excluded"?"excluded":status==="unknown_verifiable"?"open":"accepted_for_draft",createdAt:now,updatedAt:now});if(calibrationComplete(next)){next.businessCalibration.status="complete";next.businessCalibration.completedAt=now;}next.updated_at=now;return next;}
