import type { Assessment, AssessmentQuestion, CapturedFact, DiscoveryIssue, FactValue } from "@/types/assessment";

export type UncertaintyChoice="benchmark"|"estimate"|"unknown"|"exclude";
const uncertain=/\b(?:i\s+don['â€™]?t\s+know|unknown|not\s+sure|need\s+to\s+check|ask\s+me\s+later|skip\s+for\s+now|use\s+(?:the\s+)?(?:industry\s+)?(?:average|benchmark)|exclude\s+this|rough\s+guess|estimate)\b/i;
const id=()=>typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`issue-${Date.now()}-${Math.random().toString(36).slice(2)}`;
export const detectsUncertainty=(answer:string)=>uncertain.test(answer);
export function inferUncertaintyChoice(answer:string):UncertaintyChoice|undefined { if (/exclude/i.test(answer)) return "exclude"; if (/benchmark|industry average/i.test(answer)) return "benchmark"; if (/rough|estimate|about|approximately/i.test(answer)) return "estimate"; if (/unknown|don['â€™]?t know|not sure|check|later|skip/i.test(answer)) return "unknown"; }
const area=(q:AssessmentQuestion)=>q.module.replaceAll("_"," ").replace(/^./,(v)=>v.toUpperCase());
export function createDiscoveryIssue(question:AssessmentQuestion,answer:string):DiscoveryIssue { const now=new Date().toISOString(); return {id:id(),issueType:"missing_information",label:question.title,description:`The requested information was not available during discovery. User response: ${answer}`,businessArea:area(question),relatedReportSection:question.module.replaceAll("_"," "),requestedValue:question.field,currentValue:undefined,unit:"not specified",timePeriod:"Current assessment",sourceType:"unknown_verifiable",confidence:"unknown",verificationSources:[],recommendedNextAction:"Collect the value from the process owner, source system, or operating report.",effectOnReadiness:"Minimal credit until verified.",effectOnScoring:"Do not treat this variable as a confirmed scoring input.",notes:answer,status:"open",createdAt:now,updatedAt:now}; }
export function uncertaintyPrompt(issue:DiscoveryIssue) { if(issue.issueType==="user_estimate")return `Enter your rough estimate for â€œ${issue.label}â€, including a unit and time period if possible.`; return `Thatâ€™s fine. For â€œ${issue.label}â€ we can handle this in one of four ways:\n1. Use an industry benchmark estimate for now.\n2. Enter your rough estimate.\n3. Mark it as unknown and verifiable.\n4. Exclude this variable from scoring until you collect it.\n\nWhich would you prefer?`; }
function benchmarkValue(issue:DiscoveryIssue):{value:FactValue;unit:string;source:string} { const label=issue.label.toLowerCase(); if (/response|turnaround/.test(label)) return {value:{min:24,max:72},unit:"hours",source:"Local cross-industry operating benchmark"}; if (/error|correction|rework|exception/.test(label)) return {value:{min:5,max:15},unit:"percent",source:"Local cross-industry operating benchmark"}; if (/time|duration|processing/.test(label)) return {value:{min:30,max:90},unit:"minutes",source:"Local cross-industry operating benchmark"}; return {value:"Industry range to validate",unit:"benchmark range",source:"Local industry benchmark library"}; }
function factFromIssue(issue:DiscoveryIssue,sourceType:CapturedFact["sourceType"],confidence:CapturedFact["confidence"],value:FactValue,unit:string,verificationSources:string[],answer:string):CapturedFact { return {id:id(),label:issue.label,value,unit,timePeriod:issue.timePeriod,businessArea:issue.businessArea,workflowId:issue.workflowId,sourceType,confidence,verificationSources,relatedFields:[issue.requestedValue],createdFromUserAnswer:answer,createdAt:new Date().toISOString(),needsConfirmation:sourceType==="industry_benchmark"}; }
export function resolveDiscoveryIssue(assessment:Assessment,issueId:string,answer:string) { const next=structuredClone(assessment); const issue=next.discoveryIssues.find((item)=>item.id===issueId); if(!issue)return next; const choice=inferUncertaintyChoice(answer)??(issue.issueType==="user_estimate"&&/\d/.test(answer)?"estimate":undefined); const now=new Date().toISOString(); let fact:CapturedFact|undefined;
  if(choice==="benchmark") { const benchmark=benchmarkValue(issue); Object.assign(issue,{issueType:"benchmark_assumption",sourceType:"industry_benchmark",confidence:"benchmark_assumption",currentValue:benchmark.value,unit:benchmark.unit,verificationSources:[benchmark.source],recommendedNextAction:"Confirm or replace this benchmark with company data.",effectOnReadiness:"Limited partial credit.",effectOnScoring:"May support draft prioritization only; validate before implementation.",status:"accepted_for_draft",updatedAt:now}); fact=factFromIssue(issue,"industry_benchmark","benchmark_assumption",benchmark.value,benchmark.unit,[benchmark.source],answer); }
  else if(choice==="estimate") { const range=answer.match(/([\d,.]+)\s*(?:-|to)\s*([\d,.]+)/i),single=answer.match(/[\d,.]+/); if(!range&&!single){Object.assign(issue,{issueType:"user_estimate",sourceType:"user_estimate",confidence:"estimate",status:"open",recommendedNextAction:"Enter the rough value and its unit.",updatedAt:now});next.updated_at=now;return next;} const value:FactValue=range?{min:Number(range[1].replace(/,/g,"")),max:Number(range[2].replace(/,/g,""))}:Number(single![0].replace(/,/g,"")); Object.assign(issue,{issueType:"user_estimate",sourceType:"user_estimate",confidence:range?"range":"estimate",currentValue:value,status:"accepted_for_draft",recommendedNextAction:"Verify the estimate against company records.",effectOnReadiness:"Partial credit.",effectOnScoring:"Use cautiously for draft scoring.",updatedAt:now}); fact=factFromIssue(issue,"user_estimate",range?"range":"estimate",value,issue.unit,["User estimate"],answer); }
  else if(choice==="exclude") { Object.assign(issue,{issueType:"excluded_variable",sourceType:"excluded_by_user",confidence:"excluded",status:"excluded",recommendedNextAction:"Reintroduce only if the variable becomes material or available.",effectOnReadiness:"Does not block draft completion but lowers confidence in the affected section.",effectOnScoring:"Excluded from scoring and recommendations.",updatedAt:now}); }
  else { Object.assign(issue,{issueType:"needs_verification",sourceType:"unknown_verifiable",confidence:"unknown",status:"open",recommendedNextAction:"Collect from the relevant owner or source system, then update this session.",effectOnReadiness:"Minimal credit until verified.",effectOnScoring:"Excluded from confirmed scoring inputs.",updatedAt:now}); }
  if(fact) next.capturedFacts.push(fact); next.updated_at=now; return next;
}
export function issueCounts(a:Assessment) { const facts=a.capturedFacts??[],issues=a.discoveryIssues??[]; return {confirmed:facts.filter((f)=>f.sourceType==="user_confirmed"||f.sourceType==="user_corrected").length,estimates:facts.filter((f)=>f.sourceType==="user_estimate").length,benchmarks:facts.filter((f)=>f.sourceType==="industry_benchmark").length,missing:issues.filter((i)=>i.issueType==="missing_information"&&i.status==="open").length,excluded:issues.filter((i)=>i.status==="excluded").length,conflicts:issues.filter((i)=>i.issueType==="conflicting_information"&&i.status!=="resolved").length,verification:issues.filter((i)=>["needs_verification","user_estimate","benchmark_assumption"].includes(i.issueType)&&!["verified","resolved"].includes(i.status)).length}; }
