import type { Assessment } from "@/types/assessment";
import { getReportCoverage, getSpecificAssessmentGaps } from "./report-coverage";
import { factQuality } from "./evidence";
import { calibrationComplete, getCalibrationProfile } from "./calibration";

export const getReadinessSections = getReportCoverage;
export function calculateReadiness(a: Assessment) {
  const sections=getReportCoverage(a),coverage=sections.filter((section)=>section.complete).length/sections.length,facts=a.capturedFacts??[],issues=a.discoveryIssues??[];
  const sourceQuality=facts.length?facts.reduce((sum,fact)=>sum+factQuality(fact),0)/facts.length:1,assumptions=facts.filter((fact)=>["industry_benchmark","user_estimate","unknown_verifiable","excluded_by_user"].includes(fact.sourceType)||fact.needsConfirmation).length;
  const openUnknowns=issues.filter((issue)=>issue.status==="open").length,excluded=issues.filter((issue)=>issue.status==="excluded").length,conflicts=issues.filter((issue)=>issue.issueType==="conflicting_information"&&issue.status!=="resolved").length;
  const calibrationAnswers=Object.values(a.businessCalibration?.answers??{}),qualityFor=(status:string)=>status==="exact" ? 1 : (status==="estimate"||status==="range") ? .75 : status==="benchmark" ? .45 : status==="unknown_verifiable" ? .15 : 0,calibrationQuality=calibrationAnswers.length?calibrationAnswers.reduce((sum,item)=>sum+qualityFor(item.status),0)/calibrationAnswers.length:0;
  const reviews=a.expectedWorkflowReviews??[],reviewed=reviews.filter((item)=>item.status!=="unreviewed"),included=reviews.filter((item)=>item.status==="exists"||item.status==="missed_add"),estimated=included.filter((item)=>item.estimatedAnnualVolume&&item.estimatedAnnualHours),benchmarkIncluded=included.filter((item)=>item.sourceType==="industry_benchmark"||item.confidence==="benchmark_assumption");
  const calibrated=calibrationComplete(a),methodologyChecks=[a.websiteDiscovery.status==="confirmed",Boolean(a.company_profile.company_name&&a.company_profile.industry),calibrated,Boolean(a.websiteDiscovery.services.length||a.company_profile.revenue_sources.length),reviews.length>0,reviewed.length===reviews.length,included.length>0&&estimated.length===included.length,included.every((item)=>(item.commonSystems?.length??0)>0),included.every((item)=>(item.commonPainPoints?.length??0)>0),included.every((item)=>Boolean(item.sourceType&&item.confidence)),a.opportunities.length>=included.length&&included.length>0];
  const methodologyPercent=Math.round(methodologyChecks.filter(Boolean).length/methodologyChecks.length*100),benchmarkShare=included.length?benchmarkIncluded.length/included.length:0,issuePenalty=Math.min(.25,openUnknowns*.025+conflicts*.05);
  let score=(methodologyPercent/100*.85+coverage*.15)*(facts.length ? .8+.2*sourceQuality : 1)*(calibrationAnswers.length ? .85+.15*calibrationQuality : 1)-issuePenalty;
  if(!calibrated)score=Math.min(score,.45);if(reviewed.length<reviews.length||!reviews.length)score=Math.min(score,.6);if(benchmarkShare>.5)score=Math.min(score,.88);if(openUnknowns||conflicts)score=Math.min(score,.9);if(assumptions||excluded)score=Math.min(score,.97);score=Math.max(0,Math.min(1,score));
  return {score,percent:Math.round(score*100),methodologyPercent,calibrationComplete:calibrated,calibrationAnsweredCount:calibrationAnswers.length,calibrationRequiredCount:getCalibrationProfile(a.company_profile.industry).fields.filter((field)=>field.required).length,reviewedWorkflowCount:reviewed.length,expectedWorkflowCount:reviews.length,scopedMaterialWorkflowCount:estimated.length,materialWorkflowCount:included.length,benchmarkWorkflowShare:benchmarkShare,sourceQualityPercent:Math.round(sourceQuality*100),assumptionCount:assumptions,openUnknownCount:openUnknowns,excludedCount:excluded,conflictCount:conflicts,sections,missingFields:getSpecificAssessmentGaps(a)};
}
