import type { Assessment } from "@/types/assessment";
import { getReportCoverage, getSpecificAssessmentGaps } from "./report-coverage";
import { factQuality } from "./evidence";

export const getReadinessSections = getReportCoverage;
export function calculateReadiness(a: Assessment) {
  const sections = getReportCoverage(a); const completed = sections.filter((section) => section.complete).length; const coverage=completed/sections.length; const facts=a.capturedFacts ?? [];
  const issues=a.discoveryIssues??[]; const sourceQuality=facts.length ? facts.reduce((sum,fact)=>sum+factQuality(fact),0)/facts.length : 1; const assumptions=facts.filter((fact)=>fact.sourceType==="industry_benchmark"||fact.sourceType==="user_estimate"||fact.sourceType==="unknown_verifiable"||fact.sourceType==="excluded_by_user"||fact.needsConfirmation).length;
  const openUnknowns=issues.filter((issue)=>issue.status==="open").length,excluded=issues.filter((issue)=>issue.status==="excluded").length,conflicts=issues.filter((issue)=>issue.issueType==="conflicting_information"&&issue.status!=="resolved").length;
  const reviews=a.expectedWorkflowReviews??[],reviewed=reviews.filter((item)=>item.status!=="unreviewed"),included=reviews.filter((item)=>item.status==="exists"||item.status==="missed_add"),estimated=included.filter((item)=>item.estimatedAnnualVolume&&item.estimatedAnnualHours),benchmarkIncluded=included.filter((item)=>item.sourceType==="industry_benchmark"||item.confidence==="benchmark_assumption");const methodologyChecks=[a.websiteDiscovery.status==="confirmed",Boolean(a.company_profile.company_name&&a.company_profile.industry),Boolean(a.company_profile.employee_count||a.company_profile.annual_revenue||a.company_profile.locations),Boolean(a.websiteDiscovery.services.length||a.company_profile.revenue_sources.length),reviews.length>0,reviewed.length===reviews.length,included.length>0&&estimated.length===included.length,included.every((item)=>(item.commonSystems?.length??0)>0),included.every((item)=>(item.commonPainPoints?.length??0)>0),included.every((item)=>Boolean(item.sourceType&&item.confidence)),a.opportunities.length>=included.length&&included.length>0];const methodologyPercent=Math.round(methodologyChecks.filter(Boolean).length/methodologyChecks.length*100),benchmarkShare=included.length?benchmarkIncluded.length/included.length:0;
  const issuePenalty=Math.min(.25,openUnknowns*.025+conflicts*.05);let score=(methodologyPercent/100*.85+coverage*.15)*(facts.length ? (0.8+0.2*sourceQuality) : 1)-issuePenalty;if(reviewed.length<reviews.length||!reviews.length)score=Math.min(score,.6);if(benchmarkShare>.5)score=Math.min(score,.88);if(openUnknowns||conflicts)score=Math.min(score,.9);if(assumptions||excluded)score=Math.min(score,.97);score=Math.max(0,Math.min(1,score));
  return {score,percent:Math.round(score*100),methodologyPercent,reviewedWorkflowCount:reviewed.length,expectedWorkflowCount:reviews.length,scopedMaterialWorkflowCount:estimated.length,materialWorkflowCount:included.length,benchmarkWorkflowShare:benchmarkShare,sourceQualityPercent:Math.round(sourceQuality*100),assumptionCount:assumptions,openUnknownCount:openUnknowns,excludedCount:excluded,conflictCount:conflicts,sections,missingFields:getSpecificAssessmentGaps(a)};
}
