import type { Assessment } from "@/types/assessment";
import { getReportCoverage, getSpecificAssessmentGaps } from "./report-coverage";
import { factQuality } from "./evidence";
import { isWorkflowScoped } from "./workflow-methodology";

export const getReadinessSections = getReportCoverage;
export function calculateReadiness(a: Assessment) {
  const sections = getReportCoverage(a); const completed = sections.filter((section) => section.complete).length; const coverage=completed/sections.length; const facts=a.capturedFacts ?? [];
  const issues=a.discoveryIssues??[]; const sourceQuality=facts.length ? facts.reduce((sum,fact)=>sum+factQuality(fact),0)/facts.length : 1; const assumptions=facts.filter((fact)=>fact.sourceType==="industry_benchmark"||fact.sourceType==="user_estimate"||fact.sourceType==="unknown_verifiable"||fact.sourceType==="excluded_by_user"||fact.needsConfirmation).length;
  const openUnknowns=issues.filter((issue)=>issue.status==="open").length,excluded=issues.filter((issue)=>issue.status==="excluded").length,conflicts=issues.filter((issue)=>issue.issueType==="conflicting_information"&&issue.status!=="resolved").length;
  const reviews=a.expectedWorkflowReviews??[],reviewed=reviews.filter((item)=>item.status!=="unreviewed"),material=a.workflows.filter((workflow)=>workflow.materiality_status!=="not_material"),scoped=material.filter(isWorkflowScoped); const methodologyChecks=[a.websiteDiscovery.status==="confirmed",Boolean(a.company_profile.company_name&&a.company_profile.industry),reviews.length>0&&reviewed.length===reviews.length,!reviews.some((item)=>item.status==="needs_discussion"),material.length>=3,material.length>0&&scoped.length===material.length,material.every((workflow)=>workflow.systems_used.length&&((workflow.data_sources?.length??0)>0||workflow.documents_used.length)),material.every((workflow)=>(workflow.weekly_time_cost_hours??0)>0||(workflow.monthly_volume??0)>0),material.every((workflow)=>workflow.bottlenecks.length>0),a.opportunities.length>=material.length&&material.length>0,material.every((workflow)=>Boolean(workflow.sourceType&&workflow.confidence))]; const methodologyPercent=Math.round(methodologyChecks.filter(Boolean).length/methodologyChecks.length*100);
  const issuePenalty=Math.min(.3,openUnknowns*.025+excluded*.015+conflicts*.05); let score=coverage*(facts.length ? 0.65+0.35*sourceQuality : 1)*(0.45+0.55*methodologyPercent/100)-issuePenalty; if(reviewed.length<reviews.length||!reviews.length)score=Math.min(score,.65);if(scoped.length<3)score=Math.min(score,.79);if (assumptions||openUnknowns||excluded||conflicts) score=Math.min(score,.97); score=Math.max(0,Math.min(1,score));
  return { score, percent:Math.round(score*100), methodologyPercent, reviewedWorkflowCount:reviewed.length,expectedWorkflowCount:reviews.length,scopedMaterialWorkflowCount:scoped.length,materialWorkflowCount:material.length, sourceQualityPercent:Math.round(sourceQuality*100), assumptionCount:assumptions, openUnknownCount:openUnknowns, excludedCount:excluded, conflictCount:conflicts, sections, missingFields:getSpecificAssessmentGaps(a) };
}
