import rawSample from "@/sample-data/iona-hospitality.json";
import { createEmptyAssessment } from "./initial-state";
import { buildRoadmapPhases, opportunityFromWorkflow } from "./scoring";
import type { Assessment, Score } from "@/types/assessment";

export function createIonaAssessment(): Assessment {
  const empty=createEmptyAssessment(); const sample=structuredClone(rawSample);
  const state = { ...empty, ...sample, company_profile:{...empty.company_profile,...sample.company_profile}, id: "iona-hospitality-sample", answers: [] } as Assessment;
  state.capturedFacts = state.capturedFacts ?? [];
  state.websiteDiscovery={...state.websiteDiscovery,status:"confirmed",companyName:state.company_profile.company_name,industry:state.company_profile.industry,businessDescription:state.company_profile.operating_model,likelyBusinessFunctions:state.business_functions.map((item)=>item.function_name),likelyWorkflows:state.workflows.map((item)=>item.workflow_name),confirmedAt:new Date().toISOString()};
  const calibratedAt=new Date().toISOString();state.businessCalibration={status:"complete",industryKey:"hospitality",completedAt:calibratedAt,answers:{annual_revenue:{fieldId:"annual_revenue",value:state.company_profile.annual_revenue,unit:"USD/year",status:"exact",sourceType:"user_confirmed",confidence:"exact",updatedAt:calibratedAt},employee_count:{fieldId:"employee_count",value:state.company_profile.employee_count,unit:"people",status:"exact",sourceType:"user_confirmed",confidence:"exact",updatedAt:calibratedAt},locations:{fieldId:"locations",value:state.company_profile.locations,unit:"locations",status:"exact",sourceType:"user_confirmed",confidence:"exact",updatedAt:calibratedAt}}};
  state.expectedWorkflowReviews=state.workflows.map((workflow,index)=>{const annualVolume=(workflow.monthly_volume??12)*12,annualHours=Math.round((workflow.weekly_time_cost_hours??1)*52);return {id:`iona-workflow-review-${index}`,workflowName:workflow.workflow_name,businessFunction:workflow.function_name,description:workflow.ai_candidate_notes,steps:workflow.steps,inputs:workflow.inputs,outputs:workflow.outputs,commonRoles:workflow.people_involved,commonSystems:workflow.systems_used,documentsAndData:[...workflow.documents_used,...(workflow.data_sources??[])],commonPainPoints:workflow.bottlenecks,aiOpportunities:workflow.suggested_ai_use_cases??[workflow.ai_candidate_notes],complexityFactors:workflow.implementation_dependencies??[],verificationSources:["Iona sample discovery data"],estimatedAnnualVolume:{min:annualVolume,max:annualVolume,unit:"items"},estimatedAnnualHours:{min:annualHours,max:annualHours},rationale:"Confirmed in the Iona sample discovery data.",sourceType:"user_confirmed",confidence:"exact",sourceUrls:[],status:"exists",materialityReasons:["Confirmed material sample workflow"],relatedWorkflowId:workflow.workflow_name,reviewedAt:new Date().toISOString()};});
  state.workflows=state.workflows.map((workflow)=>({...workflow,sourceType:"user_confirmed",confidence:"exact",materiality_status:"material",materiality_reasons:["Confirmed material sample workflow"],verification_sources:workflow.verification_sources??["Iona sample discovery data"],number_people_involved:workflow.number_people_involved??workflow.people_involved.length,seasonality:workflow.seasonality??"Captured in sample notes",exception_rate_percent:workflow.exception_rate_percent??null,cycle_time:workflow.cycle_time??"Captured in sample baseline",suggested_ai_use_cases:workflow.suggested_ai_use_cases?.length?workflow.suggested_ai_use_cases:[workflow.ai_candidate_notes],success_measures:workflow.success_measures?.length?workflow.success_measures:["Time saved","Quality improved"]}));
  state.pain_points = state.workflows.map((workflow) => ({ pain_point:workflow.bottlenecks[0], function_name:workflow.function_name, workflow_name:workflow.workflow_name, who_feels_it:workflow.people_involved, frequency:workflow.frequency, severity:Math.max(workflow.error_or_rework_level,workflow.customer_impact,workflow.financial_impact) as Score, time_cost:workflow.weekly_time_cost_hours ? `${workflow.weekly_time_cost_hours} hours/week` : "Not quantified", dollar_cost:workflow.business_impact ?? "Not quantified", customer_impact:workflow.customer_impact, employee_impact:4 as Score, current_workaround:"Manual review and spreadsheets", root_cause:workflow.bottlenecks[0] }));
  state.opportunities = state.workflows.map((workflow) => opportunityFromWorkflow(workflow, state)).sort((a, b) => b.total_score - a.total_score);
  state.roadmap_phases = buildRoadmapPhases(state.opportunities);
  state.updated_at = new Date().toISOString();
  return state;
}
