export interface StandardWorkflowDefinition { name:string; functionName:string; description:string; steps:string[]; inputs:string[]; outputs:string[]; roles:string[]; systems:string[]; documents:string[]; volumeDrivers:string[]; baseAnnualVolume:{min:number;max:number;unit:string}; minutesPerItem:{min:number;max:number}; painPoints:string[]; aiOpportunities:string[]; complexityFactors:string[]; verificationSources:string[]; }
const common={systems:["Email","Spreadsheets","Document storage"],documents:["Forms","Emails","Status records"],complexityFactors:["Data access","System integration","Process consistency","Change adoption"],verificationSources:["Process owner","System report","Calendar or work queue","Sample documents"]};
const workflow=(name:string,functionName:string,description:string,steps:string[],volume:[number,number,string],minutes:[number,number],roles:string[],extras:Partial<StandardWorkflowDefinition>={}):StandardWorkflowDefinition=>({name,functionName,description,steps,inputs:extras.inputs??["Request or triggering event","Customer or operating data"],outputs:extras.outputs??["Completed work item","Updated status and records"],roles,systems:extras.systems??common.systems,documents:extras.documents??common.documents,volumeDrivers:extras.volumeDrivers??["Employee count","Customer or transaction volume","Service mix"],baseAnnualVolume:{min:volume[0],max:volume[1],unit:volume[2]},minutesPerItem:{min:minutes[0],max:minutes[1]},painPoints:extras.painPoints??["Manual follow-up","Repeated data entry","Status visibility","Exceptions and rework"],aiOpportunities:extras.aiOpportunities??["Drafting and summarization","Automated classification and routing","Follow-up reminders","Exception reporting"],complexityFactors:extras.complexityFactors??common.complexityFactors,verificationSources:extras.verificationSources??common.verificationSources});
const standardSteps=(subject:string)=>[`Identify ${subject} requiring action`,`Collect required information and documents`,`Prepare or process the work`,`Review decisions and exceptions`,`Communicate status or request follow-up`,`Finalize, store, and update the system of record`,`Report completion and unresolved items`];
const cpa=(name:string,fn:string,volume:[number,number,string],minutes:[number,number],roles:string[],extras:Partial<StandardWorkflowDefinition>={})=>workflow(name,fn,`${name} from initial trigger through review, communication, completion, and recordkeeping.`,standardSteps(name.toLowerCase()),volume,minutes,roles,extras);
export const standardWorkflowLibraries:Record<string,StandardWorkflowDefinition[]>={
  accounting:[
    cpa("New-client intake","Client service",[30,90,"clients"],[120,300],["Administrative staff","Managers","Partners"]),
    cpa("Engagement letter creation and renewal","Client service",[400,700,"engagements"],[15,30],["Administrative staff","Tax managers","Partners"],{steps:["Identify clients requiring engagement letters","Prepare or update the letter","Send for signature","Track signature status","Follow up on missing or incomplete letters","Correct errors or reissue letters","Store the completed letter","Update billing or project status"],systems:["Practice management","E-signature","Email","Client portal"],documents:["Engagement-letter templates","Signed engagement letters","Client records"],aiOpportunities:["Letter drafting","Status tracking","Follow-up reminders","Exception summaries","Renewal dashboard"]}),
    cpa("Tax organizer and document request","Tax",[500,1400,"organizers"],[20,45],["Tax administrators","Tax professionals","Clients"]),
    cpa("Tax return preparation","Tax",[500,1400,"returns"],[120,360],["Tax preparers","Tax managers"]),
    cpa("Tax return review","Tax",[500,1400,"returns"],[45,150],["Tax managers","Partners"]),
    cpa("E-file authorization and filing","Tax",[500,1400,"returns"],[10,25],["Tax administrators","Tax professionals"]),
    cpa("Client document follow-up","Client service",[900,2800,"follow-ups"],[8,20],["Administrative staff","Tax professionals"]),
    cpa("CAS and monthly accounting close","Client accounting",[240,720,"monthly closes"],[180,480],["Bookkeepers","CAS managers"]),
    cpa("Financial statement preparation","Accounting",[120,480,"statements"],[90,300],["Accountants","Managers"]),
    cpa("Audit and assurance planning","Assurance",[20,100,"engagements"],[360,900],["Audit seniors","Managers","Partners"]),
    cpa("Audit and assurance fieldwork and review","Assurance",[20,100,"engagements"],[1200,4800],["Audit staff","Seniors","Managers","Partners"]),
    cpa("Advisory project intake","Advisory",[20,100,"projects"],[120,360],["Advisors","Managers","Partners"]),
    cpa("Billing and collections","Finance",[600,2400,"invoices"],[10,30],["Billing staff","Managers","Partners"]),
    cpa("Client portal and document management","Administration",[1200,5000,"document events"],[4,12],["Administrative staff","Professionals"]),
    cpa("Deadline tracking","Operations",[1000,4000,"deadlines"],[3,10],["Administrative staff","Managers"]),
    cpa("Seasonal staffing and workload planning","People",[8,30,"planning cycles"],[240,600],["Operations leaders","Managers","Partners"]),
    cpa("New-hire onboarding and training","People",[5,25,"hires"],[480,1200],["HR","Managers","Trainers"]),
    cpa("Knowledge and SOP management","Operations",[30,120,"updates"],[60,240],["Managers","Subject-matter experts"])
  ],
  law:[workflow("Matter intake and conflict checking","Client intake","Qualify a potential matter, check conflicts, establish terms, and open the matter.",standardSteps("new matters"),[120,500,"matters"],[45,150],["Intake staff","Attorneys","Partners"],{systems:["Practice management","CRM","Conflict database","E-signature"],documents:["Intake forms","Conflict records","Engagement agreements"]}),workflow("Legal document drafting and review","Legal delivery","Draft, revise, approve, and file or deliver legal documents.",standardSteps("legal documents"),[500,3000,"documents"],[45,240],["Associates","Paralegals","Partners"]),workflow("Discovery and document review","Litigation","Collect, classify, review, and summarize discovery material.",standardSteps("discovery documents"),[2000,20000,"documents"],[3,15],["Paralegals","Associates","Partners"]),workflow("Matter status communication","Client service","Prepare and deliver client matter updates.",standardSteps("matter updates"),[500,3000,"updates"],[10,30],["Attorneys","Paralegals"]),workflow("Time capture, billing, and collections","Finance","Capture time, prepare invoices, resolve edits, and collect balances.",standardSteps("billing records"),[1000,6000,"billing records"],[5,20],["Attorneys","Billing staff","Partners"]),workflow("Court and deadline tracking","Operations","Monitor dates, assign actions, and confirm completion.",standardSteps("deadlines"),[500,3000,"deadlines"],[3,12],["Paralegals","Attorneys"]),workflow("Knowledge and precedent management","Operations","Store, classify, retrieve, and update reusable legal knowledge.",standardSteps("knowledge assets"),[100,600,"assets"],[20,90],["Attorneys","Knowledge staff"])],
  hospitality:[workflow("Reservations and guest inquiries","Guest service","Handle reservation requests, questions, changes, and confirmations.",standardSteps("guest requests"),[3000,15000,"requests"],[4,12],["Hosts","Front desk","Managers"]),workflow("Staff scheduling","People","Forecast staffing demand, build schedules, resolve gaps, and communicate changes.",standardSteps("schedule periods"),[52,156,"schedules"],[120,360],["Managers","Supervisors"]),workflow("Purchasing and inventory","Operations","Forecast, order, receive, reconcile, and report supplies.",standardSteps("purchase and inventory events"),[500,3000,"events"],[10,30],["Managers","Kitchen or operations staff"]),workflow("Guest feedback and service recovery","Guest service","Monitor feedback, classify issues, respond, and track corrective action.",standardSteps("reviews and complaints"),[300,2000,"items"],[8,25],["Managers","Guest service staff"]),workflow("Event and group booking","Sales","Qualify, quote, contract, plan, and coordinate events.",standardSteps("event inquiries"),[50,400,"events"],[90,360],["Sales","Events staff","Managers"]),workflow("Invoice and payment reconciliation","Finance","Reconcile transactions, exceptions, refunds, and deposits.",standardSteps("payment exceptions"),[300,2400,"items"],[8,25],["Finance staff","Managers"])],
  staffing:[workflow("Client job intake","Sales","Capture role requirements, approvals, terms, and sourcing plan.",standardSteps("job orders"),[100,600,"job orders"],[45,120],["Account managers","Recruiters"]),workflow("Candidate sourcing and screening","Recruiting","Source, review, contact, and screen candidates.",standardSteps("candidates"),[2000,12000,"candidates"],[8,30],["Recruiters","Sourcers"]),workflow("Interview scheduling","Recruiting","Coordinate candidate and client calendars and changes.",standardSteps("interviews"),[500,4000,"interviews"],[5,18],["Recruiting coordinators","Recruiters"]),workflow("Candidate submission and client follow-up","Recruiting","Prepare submissions, track feedback, and coordinate next steps.",standardSteps("submissions"),[500,4000,"submissions"],[10,30],["Recruiters","Account managers"]),workflow("Placement onboarding and compliance","Operations","Collect documents, verify requirements, and activate a placement.",standardSteps("placements"),[100,1000,"placements"],[45,150],["Coordinators","Compliance staff"]),workflow("Timesheet, payroll, and billing exceptions","Finance","Collect time, resolve exceptions, process payroll, and bill clients.",standardSteps("timesheets"),[2000,15000,"timesheets"],[3,12],["Payroll","Billing","Recruiters"])],
  professional_services:[workflow("Lead qualification and proposal development","Sales","Qualify opportunities and prepare scoped proposals.",standardSteps("opportunities"),[100,600,"opportunities"],[60,240],["Business development","Consultants","Partners"]),workflow("Project intake and staffing","Delivery","Open projects, assign resources, and confirm delivery plans.",standardSteps("projects"),[50,300,"projects"],[90,240],["Project managers","Practice leaders"]),workflow("Project delivery and status reporting","Delivery","Coordinate work, decisions, risks, deliverables, and status updates.",standardSteps("status cycles"),[500,3000,"status cycles"],[30,120],["Consultants","Project managers"]),workflow("Knowledge and deliverable reuse","Operations","Find, adapt, review, and store reusable knowledge.",standardSteps("knowledge requests"),[500,3000,"requests"],[10,45],["Consultants","Knowledge managers"]),workflow("Time, expense, billing, and collections","Finance","Capture effort, approve charges, invoice, and collect.",standardSteps("billing records"),[1000,6000,"records"],[5,20],["Consultants","Finance","Partners"])],
  construction:[workflow("Lead intake and estimating","Sales","Qualify requests, inspect requirements, estimate, and issue proposals.",standardSteps("estimates"),[100,800,"estimates"],[60,300],["Estimators","Owners","Project managers"]),workflow("Scheduling and dispatch","Operations","Assign crews, equipment, materials, and communicate changes.",standardSteps("jobs"),[500,5000,"jobs"],[8,30],["Dispatchers","Project managers"]),workflow("Job documentation and change orders","Operations","Capture field notes, photos, changes, approvals, and status.",standardSteps("job records"),[1000,8000,"records"],[5,25],["Field staff","Project managers"]),workflow("Purchasing and materials coordination","Operations","Request, order, schedule, receive, and reconcile materials.",standardSteps("material orders"),[500,4000,"orders"],[10,35],["Project managers","Purchasing","Field supervisors"]),workflow("Safety and compliance reporting","Compliance","Collect inspections, incidents, certifications, and corrective actions.",standardSteps("compliance events"),[200,2000,"events"],[10,45],["Safety staff","Supervisors"]),workflow("Progress billing and collections","Finance","Measure progress, prepare billing, resolve exceptions, and collect.",standardSteps("invoices"),[200,1800,"invoices"],[20,60],["Project managers","Finance"]),workflow("Customer updates and follow-up","Customer service","Communicate schedules, status, changes, completion, and warranty issues.",standardSteps("customer updates"),[1000,6000,"updates"],[5,20],["Coordinators","Project managers"])],
  manufacturing:[workflow("Customer order processing","Sales operations","Capture, validate, schedule, and confirm customer orders.",standardSteps("orders"),[1000,10000,"orders"],[5,20],["Customer service","Planning"]),workflow("Demand and production planning","Operations","Forecast demand, plan capacity, schedule production, and resolve constraints.",standardSteps("planning cycles"),[52,260,"cycles"],[120,480],["Planners","Operations managers"]),workflow("Purchasing and supplier follow-up","Supply chain","Plan requirements, issue orders, track delivery, and resolve exceptions.",standardSteps("purchase orders"),[500,5000,"orders"],[10,30],["Buyers","Planners"]),workflow("Inventory reconciliation","Operations","Count, compare, investigate, adjust, and report inventory.",standardSteps("inventory events"),[500,5000,"events"],[8,30],["Warehouse staff","Finance","Planners"]),workflow("Quality inspection and nonconformance","Quality","Inspect output, record results, route exceptions, and manage corrective action.",standardSteps("inspections"),[1000,10000,"inspections"],[5,25],["Inspectors","Quality engineers"]),workflow("Shipping and delivery coordination","Distribution","Plan shipments, prepare documents, track delivery, and resolve exceptions.",standardSteps("shipments"),[1000,10000,"shipments"],[5,20],["Warehouse","Customer service"]),workflow("Invoice matching and payment exceptions","Finance","Match documents, investigate exceptions, approve, and post transactions.",standardSteps("invoices"),[1000,10000,"invoices"],[4,15],["Accounts payable","Purchasing"]) ]
};
export function libraryKey(industry:string){const lower=industry.toLowerCase();if(/cpa|account|tax/.test(lower))return "accounting";if(/law|legal|attorney/.test(lower))return "law";if(/restaurant|hospital|hotel/.test(lower))return "hospitality";if(/staff|recruit|talent/.test(lower))return "staffing";if(/manufactur|distribution|warehouse/.test(lower))return "manufacturing";if(/construct|trade|contract|hvac|plumb|electric/.test(lower))return "construction";return "professional_services";}
export const getStandardWorkflows=(industry:string)=>standardWorkflowLibraries[libraryKey(industry)]??standardWorkflowLibraries.professional_services;
