import type { WebsitePage } from "./website-ingestion";

export interface WebsiteAnalysis { companyName:string; industry:string; businessDescription:string; services:string[]; customerSegments:string[]; locations:string[]; leadershipClues:string[]; revenueModelClues:string[]; hiringSignals:string[]; serviceDeliveryModel:string[]; likelyBusinessFunctions:string[]; likelyWorkflows:string[]; technologyMentioned:string[]; complianceConstraints:string[]; differentiators:string[]; sourceUrls:string[]; }
const uniq=(items:string[])=>[...new Set(items.map((item)=>item.trim()).filter(Boolean))].slice(0,12);
const snippets=(text:string,re:RegExp)=>uniq((text.match(new RegExp(`[^.!?]{0,80}${re.source}[^.!?]{0,120}[.!?]`,"gi")) ?? []).map((item)=>item.trim()));
const mentioned=(text:string,items:string[])=>items.filter((item)=>new RegExp(`\\b${item.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"i").test(text));
export function analyzeWebsite(pages:WebsitePage[]):WebsiteAnalysis {
  const home=pages[0] ?? {url:"",title:"",text:""}; const text=pages.map((p)=>p.text).join(" "); const lower=text.toLowerCase();
  const companyName=(home.title.split(/\s+[|â€“â€”:-]\s+/)[0] || new URL(home.url).hostname.replace(/^www\./,"").split(".")[0]).trim();
  const industries:[string,string[]][]=[["CPA/accounting firms",["accounting","cpa","tax preparation","audit"]],["Restaurants/hospitality",["restaurant","hotel","hospitality","resort"]],["Law firms",["attorney","law firm","legal services"]],["Staffing/recruiting firms",["staffing","recruiting","talent placement"]],["Light manufacturing/distribution",["manufacturing","distribution","warehouse"]],["Construction/trades/service businesses",["construction","contractor","plumbing","electrical","hvac"]],["Professional services firms",["consulting","advisory","professional services"]]];
  const industry=industries.find(([,keys])=>keys.some((key)=>lower.includes(key)))?.[0] ?? "";
  const serviceTerms=mentioned(text,["tax","audit","bookkeeping","wealth management","consulting","advisory","litigation","recruiting","staffing","manufacturing","distribution","construction","catering","lodging","training","managed services"]);
  const tech=mentioned(text,["QuickBooks","Microsoft 365","Salesforce","HubSpot","NetSuite","Xero","Toast","Square","Clio","Procore","Workday","SAP","Oracle","Google Workspace"]);
  const compliance=mentioned(text,["HIPAA","GDPR","SOC 2","PCI DSS","FINRA","SEC","IRS","OSHA","ISO","attorney-client privilege"]);
  const functions=["Sales","Marketing","Service delivery","Finance","Operations"];
  if (/career|join our team|hiring|open position/.test(lower)) functions.push("People and HR");
  if (/support|customer service|client service/.test(lower)) functions.push("Customer service");
  const workflows=uniq([...serviceTerms.map((s)=>`${s} service delivery`),...(lower.includes("contact")?["Lead intake and follow-up"]:[]),...(lower.includes("appointment")||lower.includes("schedule")?["Scheduling and appointment management"]:[]),...(lower.includes("invoice")||lower.includes("payment")?["Billing and collections"]:[])]);
  return {companyName,industry,businessDescription:home.text.slice(0,500),services:serviceTerms,customerSegments:mentioned(text,["individuals","families","small businesses","business owners","nonprofits","government","enterprise","healthcare","restaurants","manufacturers"]),locations:snippets(text,/(?:located|locations?|offices?)\b/i).slice(0,6),leadershipClues:snippets(text,/(?:founder|president|chief executive|managing partner|leadership)\b/i).slice(0,6),revenueModelClues:mentioned(text,["subscription","retainer","hourly","fixed fee","membership","commission","project-based","transaction fee"]),hiringSignals:snippets(text,/(?:careers?|hiring|join our team|open positions?)\b/i).slice(0,6),serviceDeliveryModel:mentioned(text,["on-site","onsite","remote","virtual","in-person","self-service","managed service","advisory"]),likelyBusinessFunctions:uniq(functions),likelyWorkflows:workflows,technologyMentioned:tech,complianceConstraints:compliance,differentiators:snippets(text,/(?:specializ|trusted|award|leading|experienced|personalized|full-service|independent)\w*/i).slice(0,6),sourceUrls:pages.map((p)=>p.url)};
}
