import type { Assessment, CapturedFact, FactValue } from "@/types/assessment";
import type { WebsiteAnalysis } from "./website-analysis";
import { mergeCapturedFacts } from "./evidence.ts";
import { generateExpectedWorkflowReviews } from "./workflow-methodology.ts";

const id=()=>typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`website-${Date.now()}-${Math.random().toString(36).slice(2)}`;
function fact(label:string,value:FactValue,relatedFields:string[],sourceUrl:string):CapturedFact { return {id:id(),label,value,unit:"text",timePeriod:"Current website",businessArea:"Company profile",sourceType:"website",sourceUrl,confidence:"inferred",verificationSources:[sourceUrl],relatedFields,createdFromUserAnswer:"Public website analysis",createdAt:new Date().toISOString(),needsConfirmation:true,confirmedByUser:false}; }
const userHas=(a:Assessment,field:string)=>a.capturedFacts.some((f)=>f.sourceType==="user_confirmed"&&f.relatedFields.includes(field));
export function applyWebsiteAnalysis(assessment:Assessment,analysis:WebsiteAnalysis,inputUrl:string) {
  const next=structuredClone(assessment); const source=analysis.sourceUrls[0] || inputUrl; const facts:CapturedFact[]=[
    { ...fact("Company website",inputUrl,["company_profile.website_url"],source),sourceType:"user_confirmed",confidence:"exact",needsConfirmation:false,confirmedByUser:true,createdFromUserAnswer:inputUrl },
    ...(analysis.companyName?[fact("Company name",analysis.companyName,["company_profile.company_name"],source)]:[]),
    ...(analysis.industry?[fact("Industry",analysis.industry,["company_profile.industry"],source)]:[]),
    ...(analysis.businessDescription?[fact("Business description",analysis.businessDescription,["company_profile.operating_model"],source)]:[]),
    ...analysis.services.map((v)=>fact("Service or product",v,["company_profile.revenue_sources"],source)),
    ...analysis.customerSegments.map((v)=>fact("Customer segment",v,["company_profile.customer_types"],source)),
    ...analysis.likelyBusinessFunctions.map((v)=>fact("Likely business function",v,["business_functions"],source)),
    ...analysis.likelyWorkflows.map((v)=>fact("Likely workflow",v,["workflows"],source)),
    ...analysis.technologyMentioned.map((v)=>fact("Technology mentioned",v,["technology_stack"],source)),
    ...analysis.complianceConstraints.map((v)=>fact("Compliance constraint",v,["governance_profile.regulated_constraints"],source)),
    ...analysis.revenueModelClues.map((v)=>fact("Revenue model clue",v,["company_profile.revenue_sources"],source)),
    ...analysis.hiringSignals.map((v)=>fact("Hiring signal",v,["role_groups"],source)),
    ...analysis.serviceDeliveryModel.map((v)=>fact("Service delivery model",v,["company_profile.operating_model"],source)),
    ...analysis.differentiators.map((v)=>fact("Marketing positioning or differentiator",v,["company_profile.current_business_pressures"],source)),
  ];
  next.company_profile.website_url=inputUrl;
  if (!next.company_profile.company_name&&!userHas(next,"company_profile.company_name")) next.company_profile.company_name=analysis.companyName;
  if (!next.company_profile.industry&&!userHas(next,"company_profile.industry")) next.company_profile.industry=analysis.industry;
  if (!next.company_profile.operating_model&&!userHas(next,"company_profile.operating_model")) next.company_profile.operating_model=analysis.businessDescription;
  if (!next.company_profile.customer_types.length) next.company_profile.customer_types=analysis.customerSegments;
  if (!next.company_profile.revenue_sources.length) next.company_profile.revenue_sources=[...analysis.services,...analysis.revenueModelClues];
  next.websiteDiscovery={status:"pending_review",companyName:analysis.companyName,industry:analysis.industry,businessDescription:analysis.businessDescription,services:analysis.services,customerSegments:analysis.customerSegments,locations:analysis.locations,revenueModelClues:analysis.revenueModelClues,leadershipClues:analysis.leadershipClues,hiringSignals:analysis.hiringSignals,technologyMentioned:analysis.technologyMentioned,likelyBusinessFunctions:analysis.likelyBusinessFunctions,likelyWorkflows:analysis.likelyWorkflows,complianceConstraints:analysis.complianceConstraints,sourceUrls:analysis.sourceUrls,rejectedFactLabels:[],correctedFields:[]};
  next.capturedFacts=mergeCapturedFacts(next.capturedFacts,facts); next.expectedWorkflowReviews=generateExpectedWorkflowReviews(next,analysis); next.updated_at=new Date().toISOString(); return {assessment:next,facts};
}

export function confirmWebsiteFacts(assessment:Assessment,accept:boolean) { const next=structuredClone(assessment); next.capturedFacts=next.capturedFacts.map((fact)=>fact.sourceType==="website"&&fact.needsConfirmation?{...fact,needsConfirmation:false,confirmedByUser:accept,confidence:accept?"inferred":fact.confidence}:fact); next.updated_at=new Date().toISOString(); return next; }

export type EditableWebsiteField="companyName"|"industry"|"businessDescription"|"services"|"customerSegments"|"locations"|"revenueModelClues"|"leadershipClues"|"hiringSignals"|"technologyMentioned"|"likelyBusinessFunctions"|"likelyWorkflows"|"complianceConstraints";
const fieldMeta:Record<EditableWebsiteField,{label:string;relatedField:string;businessArea:string}>={companyName:{label:"Company name",relatedField:"company_profile.company_name",businessArea:"Company profile"},industry:{label:"Industry",relatedField:"company_profile.industry",businessArea:"Company profile"},businessDescription:{label:"Business description",relatedField:"company_profile.operating_model",businessArea:"Company profile"},services:{label:"Service or product",relatedField:"company_profile.revenue_sources",businessArea:"Company profile"},customerSegments:{label:"Customer segment",relatedField:"company_profile.customer_types",businessArea:"Company profile"},locations:{label:"Location",relatedField:"company_profile.locations",businessArea:"Company profile"},revenueModelClues:{label:"Revenue model clue",relatedField:"company_profile.revenue_sources",businessArea:"Finance"},leadershipClues:{label:"Leadership clue",relatedField:"company_profile.management_structure",businessArea:"Leadership"},hiringSignals:{label:"Hiring signal",relatedField:"role_groups",businessArea:"People and HR"},technologyMentioned:{label:"Technology mentioned",relatedField:"technology_stack",businessArea:"Technology"},likelyBusinessFunctions:{label:"Likely business function",relatedField:"business_functions",businessArea:"Operations"},likelyWorkflows:{label:"Likely workflow",relatedField:"workflows",businessArea:"Operations"},complianceConstraints:{label:"Compliance constraint",relatedField:"governance_profile.regulated_constraints",businessArea:"Governance"}};
export function updateWebsiteDiscoveryField(assessment:Assessment,field:EditableWebsiteField,value:string|string[]) { const next=structuredClone(assessment),review=next.websiteDiscovery,previous=review[field] as string|string[],meta=fieldMeta[field],now=new Date().toISOString(),sourceUrl=review.sourceUrls[0];const priorEvidence=next.capturedFacts.find((fact)=>fact.label===meta.label&&(fact.sourceType==="user_corrected"||fact.sourceType==="website"));const originalValue=priorEvidence?.originalValue??priorEvidence?.value??(Array.isArray(previous)?previous.join("; "):previous);(review as unknown as Record<string,unknown>)[field]=value;review.correctedFields=[...new Set([...(review.correctedFields??[]),field])];review.rejectedFactLabels=review.rejectedFactLabels.filter((label)=>label!==meta.label);const values=(Array.isArray(value)?value:[value]).filter((item)=>item.trim());next.capturedFacts=next.capturedFacts.filter((fact)=>!(fact.label===meta.label&&fact.sourceType==="user_corrected"&&fact.createdFromUserAnswer.startsWith("Website fact review")));for(const current of values){next.capturedFacts.push({id:id(),label:meta.label,value:current,originalValue,unit:"text",timePeriod:"Current assessment",businessArea:meta.businessArea,sourceType:"user_corrected",sourceUrl,confidence:"exact",verificationSources:sourceUrl?[sourceUrl]:["Website analysis"],relatedFields:[meta.relatedField],createdFromUserAnswer:`Website fact review correction: ${field}`,createdAt:now,needsConfirmation:false,confirmedByUser:true});}
  if(field==="companyName")next.company_profile.company_name=value as string;if(field==="industry")next.company_profile.industry=value as string;if(field==="businessDescription")next.company_profile.operating_model=value as string;if(field==="customerSegments")next.company_profile.customer_types=value as string[];if(field==="locations")next.company_profile.locations=(value as string[]).length||null;if(field==="services"||field==="revenueModelClues")next.company_profile.revenue_sources=[...new Set([...review.services,...review.revenueModelClues])];if(field==="leadershipClues")next.company_profile.management_structure=(value as string[]).join("; ");if(field==="industry"||field==="likelyWorkflows")next.expectedWorkflowReviews=generateExpectedWorkflowReviews(next);next.updated_at=now;return next; }

export function confirmWebsiteDiscovery(assessment:Assessment,review:Assessment["websiteDiscovery"]) { const next=structuredClone(assessment),now=new Date().toISOString(),rejected=new Set(review.rejectedFactLabels);next.websiteDiscovery={...review,status:"confirmed",confirmedAt:now};next.company_profile.company_name=review.companyName;next.company_profile.industry=review.industry;next.company_profile.operating_model=review.businessDescription;next.company_profile.customer_types=rejected.has("Customer segments")?[]:review.customerSegments;next.company_profile.revenue_sources=[...new Set([...(rejected.has("Services / products")?[]:review.services),...(rejected.has("Revenue model clues")?[]:review.revenueModelClues)])];next.company_profile.management_structure=rejected.has("Leadership / management clues")?"":review.leadershipClues.join("; ");
  const rejectedFactLabels=new Set(review.rejectedFactLabels.flatMap((label)=>({"Services / products":["Service or product"],"Customer segments":["Customer segment"],"Locations":["Location"],"Revenue model clues":["Revenue model clue"],"Leadership / management clues":["Leadership clue"],"Hiring / career clues":["Hiring signal"],"Technology clues":["Technology mentioned"],"Likely business functions":["Likely business function"],"Likely workflows":["Likely workflow"],"Compliance or industry constraints":["Compliance constraint"]}[label]??[label]))),correctedLabels=new Set((review.correctedFields??[]).map((field)=>fieldMeta[field as EditableWebsiteField]?.label));next.capturedFacts=next.capturedFacts.filter((fact)=>fact.sourceType!=="website"||(!rejectedFactLabels.has(fact.label)&&!correctedLabels.has(fact.label))).map((fact)=>fact.sourceType==="website"?{...fact,originalValue:fact.originalValue??fact.value,sourceType:"user_confirmed" as const,confidence:"exact" as const,needsConfirmation:false,confirmedByUser:true}:fact);next.expectedWorkflowReviews=generateExpectedWorkflowReviews(next);next.updated_at=now;return next; }
