import type { Assessment, ExpectedWorkflowReview, ExpectedWorkflowStatus, FactConfidence, FactSourceType, Score, Workflow } from "@/types/assessment";
import type { WebsiteAnalysis } from "./website-analysis";
import { findIndustryBenchmark } from "./industry-benchmarks.ts";
import { buildRoadmapPhases, opportunityFromWorkflow } from "./scoring.ts";

const id=()=>typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`workflow-review-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const functionFor=(name:string)=>/bill|invoice|collection|payroll|financial/i.test(name)?"Finance and administration":/hire|candidate|staff|schedule/i.test(name)?"People and workforce":/lead|sales|proposal|intake/i.test(name)?"Sales and client intake":/inventory|purchas|production|dispatch|order/i.test(name)?"Operations":"Service delivery";
const rationale=(name:string,industry:string,size:number|null,locations:number|null)=>`Expected for ${industry||"this industry"}${size?` with approximately ${size} employees`:""}${locations&&locations>1?` across ${locations} locations`:""}; review its administrative, communication, documentation, exception, and reporting work.`;
export function generateExpectedWorkflowReviews(assessment:Assessment,analysis?:WebsiteAnalysis):ExpectedWorkflowReview[] { const benchmark=findIndustryBenchmark(assessment.company_profile.industry||analysis?.industry||""); const websiteNames=analysis?.likelyWorkflows??assessment.websiteDiscovery.likelyWorkflows??[]; const industryNames=benchmark?.commonWorkflows??[]; const existing=new Map(assessment.expectedWorkflowReviews.map((item)=>[item.workflowName.toLowerCase(),item])); const sourceUrls=analysis?.sourceUrls??assessment.websiteDiscovery.sourceUrls??[];
  return [...new Set([...websiteNames,...industryNames])].map((workflowName)=>{const prior=existing.get(workflowName.toLowerCase());if(prior)return prior;const fromWebsite=websiteNames.some((name)=>name.toLowerCase()===workflowName.toLowerCase());return {id:id(),workflowName,businessFunction:functionFor(workflowName),rationale:rationale(workflowName,assessment.company_profile.industry||analysis?.industry||"",assessment.company_profile.employee_count,assessment.company_profile.locations),sourceType:(fromWebsite?"website":"industry_benchmark") as FactSourceType,confidence:(fromWebsite?"inferred":"benchmark_assumption") as FactConfidence,sourceUrls:fromWebsite?sourceUrls:[],status:"unreviewed",materialityReasons:[]};}); }
export function materialityReasons(workflow:Workflow) { const reasons:string[]=[]; if((workflow.weekly_time_cost_hours??0)>=5)reasons.push("Consumes at least 5 company hours per week"); if((workflow.monthly_volume??0)>=50)reasons.push("Occurs at least 50 times per month"); if(workflow.error_or_rework_level>=3||workflow.bottlenecks.length)reasons.push("Creates delay, rework, follow-up, or exceptions"); if(workflow.customer_impact>=3)reasons.push("Affects customer or client experience"); if(workflow.financial_impact>=3)reasons.push("Affects revenue, cost, billing, or collections"); if(workflow.systems_used.some((item)=>/email|spreadsheet|excel|form|document/i.test(item))||workflow.documents_used.length)reasons.push("Depends on email, spreadsheets, forms, or documents"); if(workflow.decision_points.length||/draft|classif|summar|route|reconcil|report/i.test(workflow.ai_candidate_notes))reasons.push("Requires repeated judgment or information processing"); return reasons; }
function blankWorkflow(review:ExpectedWorkflowReview):Workflow { return {workflow_name:review.workflowName,function_name:review.businessFunction,owner:"",trigger:"Recurring business event",steps:[],inputs:[],outputs:[],systems_used:[],documents_used:[],people_involved:[],number_people_involved:null,frequency:"To confirm",monthly_volume:null,time_per_instance_minutes:null,weekly_time_cost_hours:null,monthly_time_cost_hours:null,annual_time_cost_hours:null,seasonality:"To confirm",exception_rate_percent:null,cycle_time:"To confirm",verification_sources:review.sourceUrls,sourceType:"user_confirmed",confidence:"exact",materiality_status:"unreviewed",materiality_reasons:[],error_or_rework_level:2 as Score,bottlenecks:[],decision_points:[],customer_impact:2 as Score,financial_impact:2 as Score,data_sensitivity:2 as Score,process_maturity:2 as Score,data_readiness:2 as Score,ai_candidate_notes:"Review planning, scheduling, communication, documentation, exceptions, reporting, compliance, quality, inventory/materials coordination, billing, and follow-up surrounding this workflow.",implementation_dependencies:[],suggested_ai_use_cases:[],success_measures:[]}; }
function rescore(next:Assessment){next.opportunities=next.workflows.filter((workflow)=>workflow.materiality_status!=="not_material").map((workflow)=>opportunityFromWorkflow(workflow,next)).sort((a,b)=>b.total_score-a.total_score);next.roadmap_phases=buildRoadmapPhases(next.opportunities);}
export function reviewExpectedWorkflow(assessment:Assessment,reviewId:string,status:ExpectedWorkflowStatus) { const next=structuredClone(assessment),review=next.expectedWorkflowReviews.find((item)=>item.id===reviewId);if(!review)return next;review.status=status;review.reviewedAt=new Date().toISOString();if(status==="exists"||status==="missed_add"){let workflow=next.workflows.find((item)=>item.workflow_name.toLowerCase()===review.workflowName.toLowerCase());if(!workflow){workflow=blankWorkflow(review);next.workflows.push(workflow);}review.relatedWorkflowId=workflow.workflow_name;}rescore(next);next.updated_at=new Date().toISOString();return next; }
export function updateWorkflowScope(assessment:Assessment,index:number,updates:Partial<Workflow>) { const next=structuredClone(assessment),workflow=next.workflows[index];if(!workflow)return next;Object.assign(workflow,updates);workflow.monthly_time_cost_hours=workflow.weekly_time_cost_hours===null?null:Math.round(workflow.weekly_time_cost_hours*4.33*10)/10;workflow.annual_time_cost_hours=workflow.weekly_time_cost_hours===null?null:Math.round(workflow.weekly_time_cost_hours*52*10)/10;workflow.number_people_involved=workflow.number_people_involved??(workflow.people_involved.length||null);workflow.materiality_reasons=materialityReasons(workflow);workflow.materiality_status=workflow.materiality_reasons.length?"material":"not_material";rescore(next);next.updated_at=new Date().toISOString();return next; }
export const isWorkflowScoped=(workflow:Workflow)=>Boolean(workflow.owner&&workflow.frequency&&workflow.systems_used.length&&(workflow.data_sources?.length||workflow.documents_used.length)&&((workflow.weekly_time_cost_hours??0)>0||(workflow.monthly_volume??0)>0)&&workflow.bottlenecks.length&&workflow.suggested_ai_use_cases?.length&&workflow.success_measures?.length&&workflow.sourceType&&workflow.confidence);
