import type { AssessmentQuestion } from "@/types/assessment";

export const deepDiscoveryQuestions: AssessmentQuestion[] = [
  { id:"operating_metrics", module:"operating_metrics", field:"operating_metrics", title:"Quantify the operating snapshot", help:"One per line: Metric | value | unit | period | source | why it matters. Include transaction/customer volume, labor, recruiting, reviews, invoices, and other scale measures.", priority:97, isComplete:(a)=>a.operating_metrics.length >= 10 },
  { id:"staffing_breakdown", module:"people_roles", field:"role_groups", title:"Complete the staffing and management breakdown", help:"List role groups, headcount, manager, responsibilities, turnover, hiring difficulty, and adoption readiness. Account for the full employee count.", priority:94, isComplete:(a)=>a.role_groups.length >= 4 && a.role_groups.reduce((sum,role)=>sum+(role.headcount??0),0) >= (a.company_profile.employee_count ?? Infinity) },
  { id:"workflow_detail", module:"workflow_detail", field:"workflows.detail", title:"A few workflow estimates still need a simple decision. Please accept, adjust, verify later, or exclude them in the workflow cards.", help:"You do not need to map the process. Review the annual volume and effort ranges and choose the action that best reflects what you know today.", priority:93, isComplete:(a)=>a.expectedWorkflowReviews.length>0&&a.expectedWorkflowReviews.every((item)=>item.status!=="unreviewed")&&a.expectedWorkflowReviews.filter((item)=>item.status==="exists"||item.status==="missed_add").every((item)=>Boolean(item.estimatedAnnualVolume&&item.estimatedAnnualHours)) },
  { id:"pain_point_detail", module:"pain_points", field:"pain_points", title:"Quantify the most material pain points", help:"Connect each pain point to a workflow, owner, frequency, severity, time or dollar cost, customer/employee impact, workaround, and root cause.", priority:89, isComplete:(a)=>a.pain_points.length >= 8 },
  { id:"baseline_metrics", module:"baseline_metrics", field:"workflows.baseline_metrics", title:"Establish baselines for the priority opportunities", help:"One per line: Workflow | metric | current baseline | data source. Include cycle time, hours, error/rework, cost, revenue, quality, or customer measures.", priority:91, isComplete:(a)=>a.workflows.slice(0,5).length >= 5 && a.workflows.slice(0,5).every((w)=>w.baseline_metrics?.length) },
  { id:"implementation_capacity", module:"implementation_capacity", field:"ai_readiness.implementation_constraints", title:"What will make implementation practical or difficult?", help:"Name owners, available capacity, budget, vendor/integration constraints, change-management needs, dependencies, and approval gates.", priority:87, isComplete:(a)=>Boolean(a.ai_readiness.implementation_capacity && a.ai_readiness.implementation_constraints?.length && a.management_decisions.length >= 3) },
  { id:"success_metrics", module:"success_metrics", field:"workflows.target_metrics", title:"Define success targets for the first projects", help:"One per line: Workflow | metric | baseline | target | measurement period | source. State what would prove the project worked.", priority:90, isComplete:(a)=>a.workflows.slice(0,5).length >= 5 && a.workflows.slice(0,5).every((w)=>w.target_metrics?.length && w.success_measures?.length) },
];
